### PR TITLE
First step to implement the new UI for the setup page.

### PR DESCRIPTION
**Pull request by blueandgold**
This PR focuses on the page structure and the underlying code structure.  There are still a lot of fine tuning to make the UI look pretty.
- Made chrome policy card into a custom element so that it can be reused on the setup page.
- This then required the resource_dicts to be moved out to its own module.
- Deleted the chrome policy page and moved the configurable settings to the setup page as well.  We talked about this a bit and I'm not sure what we'll do eventually, but putting here for now.
- I can add unit test for component_resources.py before merging if component_resources.py looks to you.

screenshot from 2016-02-24 15 36 00

[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/45)

### CODE REVIEW

**Comment by xwsxethan** [comment]
Looks nice overall! I made a couple of comments on how to bring the style closer to the new UI with colors, sizing, and positioning. I would ask you to update the web driver test to remove the chrome policy link, but the whole sidebar test will be removed shortly so I'm not too worried about it.

You'll still need to implement the new user/server add diagrams, but I assume that will be another PR. You can add TODO's for that if you like, but not critical. 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[ufo/routes.py, line 19 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLeeFCxuEe9hGXApvv:-KBLeeFCxuEe9hGXApvw:-649523204) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/routes.py#L19)):*
If these are private methods, then we really shouldn't be calling them outside of their class/module so maybe keep them private and move them here or just make them public? Also, would it make more sense for these to live alongside their associated handlers or models? I'm fine with keeping it as a separate module, but just curious on your opinion here for what is cleaner. Overall, I like cleaning them up into separate functions so the landing page handler isn't so bloated.

---

*[ufo/static/chromePolicy.html, line 1 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBL_8OmQu6aRWzR7c4A:-KBL_8OnPzM3iTVkeMde:-1496006160) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/static/chromePolicy.html#L1)):*
It doesn't really matter since we vulcanize everything together anyway, but technically you should have an import for paper-button as well.

On another note, I'm fine with moving this to a custom element, but we're eventually going to have to adjust how this works for i18n. All the text will get moved over to json, which is straightforward enough, but making the anchor link work in some random json will be tougher. Hopefully that will be a feature of whatever i18n library we use, so that we don't have to parse the translated text to find 'Google Admin Console' and wrap it. Just passing along so you're aware.

---

*[ufo/templates/setup.html, line 4 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLak7nNdqQBr0t7Q6m:-KBLak7nNdqQBr0t7Q6n:240820806) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L4)):*
You'll probably want to do this as paper-material to match what I was doing previously. I'm not sure there's much of a difference though, so it should be fairly cut and paste (I hope). You could also just use the paper-display-template again if that's easier, so long as whatever you pass into resources has a titleText field, which you could set to whatever seems appropriate.

---

*[ufo/templates/setup.html, line 4 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLbIcQ_ZG_Zi-7JGne:-KBLbIcQ_ZG_Zi-7JGnf:1207052052) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L4)):*
You'll want to wrap each top level item (so each paper card currently or paper-material from above) in its own centered div so it matches the rest. Here's the snippet I used:

<div class="horizontal center-justified layout">

You'll need separate ones for each card so they are each centered (and not in the same row as each other).

If you opt to go with using the paper-display-template, that will handle this for you.

---

*[ufo/templates/setup.html, line 12 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdyh2Bwm27aOZKSLm:-KBLdyh2Bwm27aOZKSLn:921802232) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L12)):*
Nit: spacing. There's a few of these that must have creeped in with the auto-indent.

---

*[ufo/templates/setup.html, line 29 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdxKOzkh0U5eqwxEF:-KBLdxKOzkh0U5eqwxEG:1099296581) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L29)):*
Nit: spacing.

---

*[ufo/templates/setup.html, line 43 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdwf5GQBv9KcRMGlM:-KBLdwf5GQBv9KcRMGlN:1099296581) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L43)):*
Nit: spacing.

---

*[ufo/templates/setup.html, line 50 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdw4UKCw27vi9Wi7o:-KBLdw4UKCw27vi9Wi7p:1099296581) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L50)):*
Nit: spacing.

---

*[ufo/templates/setup.html, line 51 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLcE3sKX5ZAL6cAj0X:-KBLcE3sKX5ZAL6cAj0Y:-669425666) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L51)):*
Add the anchor-no-button class here to fix the styling for the link.

---

*[ufo/templates/setup.html, line 52 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdvTAE-v0shrtGDEz:-KBLdvTAE-v0shrtGDF-:1099296581) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L52)):*
Nit: spacing.

---

*[ufo/templates/setup.html, line 57 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdu53lFDWJeeaes_H:-KBLdu53lFDWJeeaes_I:1099296581) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L57)):*
Nit: spacing.

---

*[ufo/templates/setup.html, line 63 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLbph6PVCthRNkdBYh:-KBLbph6PVCthRNkdBYi:1284225186) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L63)):*
Remove the raised attribute here and add the anchor-button class to fix the button's styling.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-:-KBLfOxpfF0Ae42hjZuT:-393475834)*

**Comment by blueandgold** [comment]
Thanks for the review!  I have addressed all the comments.  There will definitely be more work & polish here in the upcoming PRs.

---

Review status: 2 of 12 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[ufo/routes.py, line 19 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLeeFCxuEe9hGXApvv:-KBO_3y01Mpi-85Nq1ND:-466587333) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/routes.py#L19)):*
Excellent suggestion here.  But to make this work, we'll have to move all the exceptions to a new exception module, otherwise there will be a circular import here, for SetupNeeded.  see stack trace below

To be honest, I am starting to think that we need a service package (i.e. directory) where we can put helper functions like this in.  Because although putting this in the handler is better, it seems really heavyweight to import the whole user handler into setup, just to be able to use this one function.  Not super-critical right now.

```
python run.py 
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import ufo
  File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 181, in SetupPathsAndImport
    return real_import(name, globals, locals, fromlist, level)
  File "/usr/local/google/home/henryc/git/ufo-management-server-flask/ufo/__init__.py", line 79, in <module>
    from setup import SetupNeeded
  File "/usr/local/google/home/henryc/git/ufo-management-server-flask/ufo/setup.py", line 10, in <module>
    from ufo import chrome_policy
  File "/usr/local/google/home/henryc/git/ufo-management-server-flask/ufo/chrome_policy.py", line 9, in <module>
    from . import app, db, setup_required
ImportError: cannot import name setup_required
```

---

*[ufo/static/chromePolicy.html, line 1 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBL_8OmQu6aRWzR7c4A:-KBOXiaCBBGeTCisCL4N:-1457819947) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/static/chromePolicy.html#L1)):*
Done, added the paper-button import.

Ack, on the i18n.  We can finesse the html when we get there.  :)

---

*[ufo/templates/setup.html, line 4 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLak7nNdqQBr0t7Q6m:-KBOYvHW4oLzIR9eIqYa:115709417) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L4)):*
Yup, good comment.  Adding this as a TODO.  Will tackle this in next PR.

---

*[ufo/templates/setup.html, line 4 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLbIcQ_ZG_Zi-7JGne:-KBOZA9TsQAKSGr7Yl_p:197604617) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L4)):*
Ack.  Will do in next PR.

---

*[ufo/templates/setup.html, line 12 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdyh2Bwm27aOZKSLm:-KBOZFz6GfHM2AJw6lh5:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L12)):*
Done.

---

*[ufo/templates/setup.html, line 29 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdxKOzkh0U5eqwxEF:-KBOZIiN5XMb10aNU6Lj:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L29)):*
Done.

---

*[ufo/templates/setup.html, line 43 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdwf5GQBv9KcRMGlM:-KBOZKfvP45tjWFC8-Qx:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L43)):*
Done.

---

*[ufo/templates/setup.html, line 50 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdw4UKCw27vi9Wi7o:-KBOZPQTTVG3U0CULl9M:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L50)):*
Done.

---

*[ufo/templates/setup.html, line 51 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLcE3sKX5ZAL6cAj0X:-KBOZQDSScQMlZ89exaU:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L51)):*
Done.

---

*[ufo/templates/setup.html, line 52 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdvTAE-v0shrtGDEz:-KBOZXuEcGO4LwcEq6Wt:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L52)):*
Done.

---

*[ufo/templates/setup.html, line 57 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdu53lFDWJeeaes_H:-KBOZZl8s5T52vL5KqP7:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L57)):*
Done.

---

*[ufo/templates/setup.html, line 63 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLbph6PVCthRNkdBYh:-KBOZmXFDGKsnE4q1SbI:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L63)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-:-KBOlK9Jzj5J1psg1e3s:1698444627)*

**Comment by xwsxethan** [comment]
Couple of nits left, but :+1: once taken care of. Sounds good about polishing in a follow up.

---

Reviewed 10 of 11 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ufo/routes.py, line 19 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLeeFCxuEe9hGXApvv:-KBOu5E1uY3MB-iZa6bb:-765963664) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/routes.py#L19)):*
Yeah I was wondering about whether that made sense in terms of moving them. If you like them better as their own module of resource getters, then that's fine as well. I'm open to suggestions here, so if I'm way off please feel free to correct me.

---

*[ufo/templates/setup.html, line 12 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdyh2Bwm27aOZKSLm:-KBOuta1Gr4cVcEyWR3_:1283854255) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L12)):*
Nit: There's still one space leftover here.

---

*[ufo/templates/setup.html, line 51 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLcE3sKX5ZAL6cAj0X:-KBOv6bV5eyHK9lTtOdS:-992166340) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L51)):*
I don't see it here. Did you make a TODO somewhere else or miss it?

---

*[ufo/templates/setup.html, line 63 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLbph6PVCthRNkdBYh:-KBOvHyS3nKNsqRWcs-1:1001608081) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L63)):*
You can specify both classes together here with a space separating them, such as class="form-submit-button anchor-button".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-:-KBOvYeWqrwg71VAd3sW:-1075300479)*

**Comment by xwsxethan** [comment]
Sorry forgot this, but you'll want to fix the tests before merging as well. Looks like an import is missing or messed up for SetupNeeded.

**Comment by blueandgold** [comment]
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ufo/templates/setup.html, line 12 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLdyh2Bwm27aOZKSLm:-KBP4ZxNb_P1mnX3pAdL:-905103908) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L12)):*
Really done.

---

*[ufo/templates/setup.html, line 51 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLcE3sKX5ZAL6cAj0X:-KBP5OaiMuVIEs2wuMge:-905103908) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L51)):*
Really done.

---

*[ufo/templates/setup.html, line 63 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-KBLbph6PVCthRNkdBYh:-KBP5v9K5Vmh3vERWdLv:-180270900) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1725c289155889f407470fc587ba7baacc2eac08/ufo/templates/setup.html#L63)):*
Cool.  Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45)*

**Comment by blueandgold** [comment]
All taken care of, including the broken test.

---

Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45#-:-KBPBGWydlCYSsiXwak5:1319892376)*

**Comment by xwsxethan** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/45)*

**Pull request merged**
