### PR TITLE
Refactor User Add for PII

### PR DESCRIPTION
**Pull request by xwsxethan**
[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/29)

### CODE REVIEW

**Comment by xwsxethan** [comment]
@jpevarnek PTAL as well.

**Comment by jpevarnek** [comment]
@xwsxethan can you repush this with the "updating heroku" commits removed?

**Comment by blueandgold** [comment]
:+1:  Looks good to me, thanks for addressing PII here.

**Comment by jpevarnek** [comment]
Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[ufo/google_directory_service.py, line 7 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mhJ7xYACgf9_6H9yW:-K9mhJ7xYACgf9_6H9yX:-1514413132) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/google_directory_service.py#L7)):*
Probably should be `from ufo import models` to make your life a bit easier.

---

*[ufo/google_directory_service.py, line 30 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mhMpQ3J69bYkS2W0b:-K9mhMpQ3J69bYkS2W0c:-1306941138) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/google_directory_service.py#L30)):*
`get_user_config`

---

*[ufo/templates/add_user.html, line 28 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mjOTyqAQFLvltRzHl:-K9mjOTyqAQFLvltRzHm:1920463620) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/templates/add_user.html#L28)):*
My personal view is that it's much better if we stick to a more api-like submission format for sending data (e.g. `"users": [{"name": "Bob", "email": "bob@bob.com"}, {"name": "Chaz", "email": "chaz@bob.com"}]`).  Do you think that's something we can move closer to or would that be too hard here.

---

*[ufo/templates/add_user.html, line 29 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mhZKzJWdtBv6btwgb:-K9mhZKzJWdtBv6btwgc:-735514567) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/templates/add_user.html#L29)):*
To me, having "user" here twice feels a bit redundant.  It might make more sense to just have something like `user['name']` and `user['email']`.

---

*[ufo/user.py, line 55 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9miSEfkJ8axQRWw6uw:-K9miSEguO6IE520U_4D:-449499533) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/user.py#L55)):*
`stripped_user` seems a bit odd as a variable name (with that name, I'd expect a whitelist filter of properties).  Maybe something like `user_for_display` would make a bit more sense.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29)*

**Comment by xwsxethan** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[ufo/google_directory_service.py, line 7 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mhJ7xYACgf9_6H9yW:-K9msbzo5RpmoA5PuTkT:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/google_directory_service.py#L7)):*
Done.

---

*[ufo/google_directory_service.py, line 30 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mhMpQ3J69bYkS2W0b:-K9msez80oluuuQCVb5q:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/google_directory_service.py#L30)):*
Done.

---

*[ufo/templates/add_user.html, line 28 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mjOTyqAQFLvltRzHl:-K9mti1-oTpl0Ku4_jXr:-1911974154) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/templates/add_user.html#L28)):*
Yeah we can do that. I've marked the other items as done since I was able to quickly address them, but this will take some more time since it will involve collecting them via javascript. Overall, that is probably the better way to go anyway, and it will allow us to use Polymer checkboxes instead of standard ones. I'll follow back up and request another review once that's done.

---

*[ufo/templates/add_user.html, line 29 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mhZKzJWdtBv6btwgb:-K9mt_EFL_db56OH4gzr:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/templates/add_user.html#L29)):*
Done.

---

*[ufo/user.py, line 55 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9miSEfkJ8axQRWw6uw:-K9mssfS8x0wjC9aMqem:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/user.py#L55)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29)*

**Comment by jpevarnek** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ufo/templates/add_user.html, line 28 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mjOTyqAQFLvltRzHl:-KA1N4w0j_tUyi0QVPOU:1491664460) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/templates/add_user.html#L28)):*
Okay, can you add a TODO for this?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29)*

**Comment by xwsxethan** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ufo/templates/add_user.html, line 28 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mjOTyqAQFLvltRzHl:-KA1tBXxVcAhw6Hikuh-:111916992) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/templates/add_user.html#L28)):*
Oh, I was going to just do it in this PR. That's fine too though. I'll add a TODO, then submit this, and make a new PR for the change to make it more of an API format.

Look good?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29)*

**Comment by xwsxethan** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ufo/templates/add_user.html, line 28 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-K9mjOTyqAQFLvltRzHl:-KA6GsFgCHWAGw4sGJq7:-1601093023) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e00d8aa2682b26653cfe606fefc0fb52938a6a84/ufo/templates/add_user.html#L28)):*
@jpevarnek  So I know I said I would do this in a separate PR, but since this one has so much required boilerplate and isn't approved yet, I just moved the refactoring for a generic API into this. Please take a look. Thank you!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29)*

**Comment by jpevarnek** [comment]
Yup, looks fine

:thumbsup:

---

Reviewed 5 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29#-:-KAHr3mFTFtg3wF-rKme:-1315005583)*

**Comment by xwsxethan** [comment]
Reviewed 1 of 1 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/29)*

**Pull request merged**
