### PR TITLE
Use Quaintous-i18n for i18n Messages in Polymer Elements and Remove Messages from Resource Dictionary

### PR DESCRIPTION
**Pull request by xwsxethan**
A lot of Polymer elements/components are modified in this PR, but as you'll see the changes are pretty small in nature, just copied multiple times over. Each change is basically as follows:
1. Make the dom module reference a new property for the i18n message (rather than referencing resources).
2. Make the binding one way instead of two way (use square brackets [] instead of curly braces {}).
3. Set the new property inside of the attached event handler function for the dom module (have to use attached to ensure that quaintous-i18n is already loaded) using the **i18n** function from quaintous-i18n.
4. Add quaintous-i18n as a relative import. This isn't actually necessary because of how we handle vulcanization, but it is still included to show where the reference comes from.

Finally, I removed all the messages from the resource dictionary since the resource dictionary is no longer being reference for them.

---

This change is [Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/203)

### CODE REVIEW

**Comment by xwsxethan** [comment]
@blueandgold ping

**Comment by blueandgold** [comment]
:+1:  Sorry this slipped under my radar.  So, thanks for the ping.

**Comment by blueandgold** [comment]
Please make sure the webdriver stuff works for i18n.  :)

**Comment by xwsxethan** [comment]
The web driver tests do pass. They were the first thing I check once it was all done.

**Pull request merged**
