### PR TITLE
Change the schedule for the key distribution process so that it's eas…

### PR DESCRIPTION
**Pull request by blueandgold**
…ier for TT to check that this has worked.

---

This change is [Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/240)

### CODE REVIEW

**Comment by xwsxethan** [comment]
Could this eventually cause a problem if the key distribution is still running when the next process starts? Just curious with how the scheduler handles this. Also, please leave a todo to switch this back later as necessary. :+1:

**Comment by blueandgold** [comment]
Done.  Yah, the overlapping job might be a concern.  But so far, the size of our deployments take only ~10 seconds.  So, 2 minutes is plenty to finish for the foreseeable TT.  It's just a balance of waiting on verification for our TT vs robustness.  But yes, let's keep an eye on the actual deployment size and tune this.

**Comment by blueandgold** [comment]
This shows how fast the keys are distributed at the current deployment size (~5 users).

2016-08-01T20:46:14.972399+00:00 app[clock.1]: INFO:ufo:Enqueuing cron user sync job.
2016-08-01T20:46:16.990316+00:00 app[worker.1]: 20:46:16 default: _distribute_key(<ufo.database.models.ProxyServer object at 0x7fb1e4fa8090>, '') (65b26734-5cb2-4288-9826-bb0b2ef62d62)
2016-08-01T20:46:17.358103+00:00 app[worker.1]: Distributing keys to proxy server: SG-Proxy-Server

**Comment by xwsxethan** [comment]
LGTM :100:

**Pull request merged**
