### PR TITLE
Add support for SSH-ing in to remote servers

### PR DESCRIPTION
**Pull request by jpevarnek**
This adds an SSHClient class that extends the native Paramiko SSHClient.
It overrides the connect method so that it will now accept a
ProxyServer model as the argument and connect to that server.

Submitting this mostly for thoughts right now, it's pretty much just a ton of hacking around the Paramiko API to get it to do what we want.

I'm open to other ways of structuring things, this felt like a good first step though.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/16)

### CODE REVIEW

**Comment by jpevarnek** [comment]
As a note: this totally breaks the proxy server adding process.  I'll fix that :)

**Comment by xwsxethan** [comment]
What will this ssh client eventually do? I assume it is for pushing the authorized users file out to existing proxy servers right? Will it also be able to initialize the proxy server for us or is that unrelated? Also, I assume the paramiko API supplies disconnect or close or similar methods that we don't need to override which will work by default. Otherwise, looks good to me I guess.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ufo/ssh_client.py, line 27 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8_81gD0_vjPUNF_u6Z:-K8_81gD0_vjPUNF_u6_:1051156494) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/01505a7f2515a1182f5247a5ac854d31e6533146/ufo/ssh_client.py#L27)):*
Nit: punctuation.

---

*[ufo/ssh_client.py, line 32 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8_84TAJTDZmEznr8Lr:-K8_84TAJTDZmEznr8Ls:-1426979198) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/01505a7f2515a1182f5247a5ac854d31e6533146/ufo/ssh_client.py#L32)):*
Might be more obvious to name this variable proxy_server instead to alleviate your comment about passing a proxy server model as the param. Your call though.

---

*[ufo/ssh_client.py, line 70 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8_7ysQZpmCsZ-ZVW98:-K8_7ysQZpmCsZ-ZVW99:1051156494) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/01505a7f2515a1182f5247a5ac854d31e6533146/ufo/ssh_client.py#L70)):*
Nit: punctuation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-:-K8_6piIEP6sO-36eLGR:255815954)*

**Comment by goldspin** [comment]
Took an initial look and looks okay.  +1 on Ethan's question.  Perhaps document this in the module docstring?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ufo/models.py, line 95 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8aMSPt-ukDwLAOz39S:-K8aMSPuGKDtbIgnApFp:-618845493) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/01505a7f2515a1182f5247a5ac854d31e6533146/ufo/models.py#L95)):*
nit: Why use "_type"?  How about "_string" instead?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-:-K8aN1efUPJg7mlW9B09:-465611320)*

**Comment by blueandgold** [comment]
@jpevarnek If this is a breaking change, please let me submit my proxy server test PR before this.  Thanks!

**Comment by jpevarnek** [comment]
@xwsxethan All of the above and your assumptions are totally correct :)

@blueandgold okay, nothing should be breaking but the parameters, I'll wait for you on that though.

Things marked done might not actually be pushed, sorry about that, working on a few things locally to fix `proxy_server.html`

http://docs.paramiko.org/en/1.16/api/client.html

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ufo/models.py, line 95 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8aMSPt-ukDwLAOz39S:-K8aj0OqALAWHV_ERQr8:-1771095873) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/01505a7f2515a1182f5247a5ac854d31e6533146/ufo/models.py#L95)):*
This is referring to the type of key (whether it is RSA or eliptic curve for example)

---

*[ufo/ssh_client.py, line 27 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8_81gD0_vjPUNF_u6Z:-K8_JTG7_5BcaG4Ok8Gq:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/01505a7f2515a1182f5247a5ac854d31e6533146/ufo/ssh_client.py#L27)):*
Done.

---

*[ufo/ssh_client.py, line 32 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8_84TAJTDZmEznr8Lr:-K8_JNVrmpWkCn6vYEBY:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/01505a7f2515a1182f5247a5ac854d31e6533146/ufo/ssh_client.py#L32)):*
Done.

---

*[ufo/ssh_client.py, line 70 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8_7ysQZpmCsZ-ZVW98:-K8_JOt286WvNz2pVd5d:614734886) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/01505a7f2515a1182f5247a5ac854d31e6533146/ufo/ssh_client.py#L70)):*
And spelling...  Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-:-K8_Mdy1T_nxyHM8GHBI:1030302970)*

**Comment by xwsxethan** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-:-K8an8px-zA1cRlNT8ie:980077423)*

**Comment by blueandgold** [comment]
:+1:

**Comment by jpevarnek** [comment]
Okay, completely changed around...  I commented on a few areas I'm concerned about, would love some feedback there.

---

Review status: 1 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[ufo/models.py, line 112 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bFW7p9yXvGNC_v9sO:-K8bFW7qt50FTU5HyGc0:911010555) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/models.py#L112)):*
I really do not like accessing the private method here, but didn't feel like writing some string parsing since I'm nearly positive I'd make a few mistakes.  If we actually wanted to do manual parsing here, it would probably be only 20-30 lines.

Someone else should decide.

---

*[ufo/models.py, line 125 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bFnNkEjiHMAPU7iX3:-K8bFnNkEjiHMAPU7iX4:1732280711) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/models.py#L125)):*
This makes me want to cry.  On the other hand, it's the best parsing method for the file I can come up with...  Deferring to one of you on whether this is good enough.

---

*[ufo/proxy_server.py, line 42 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bG-uW5db9hv0Qlfiz:-K8bG-uW5db9hv0Qlfj-:-1503742843) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/proxy_server.py#L42)):*
This is my quick solution for representing the proxy server when showing it to a human, I'd love any ideas of how to make it cleaner though.

---

*[ufo/proxy_server.py, line 67 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGLPoPvDlnc2-VC89:-K8bGLPoPvDlnc2-VC8A:-1655421823) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/proxy_server.py#L67)):*
...this should be a list comprehension, please fix (yes, I realize I'm telling myself to do something right now, don't judge)

---

*[ufo/proxy_server.py, line 86 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGSv3bMF-T9FxxGC4:-K8bGSv3bMF-T9FxxGC5:-1521677687) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/proxy_server.py#L86)):*
I'm just leaving this as-is for now if no objections, but should really be more robust validation.

---

*[ufo/ssh_client.py, line 13 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGf5thuUmGWCpiaCs:-K8bGf5thuUmGWCpiaCt:1424570860) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/ssh_client.py#L13)):*
Better comment would be "to set up a connection", will fix.

---

*[ufo/ssh_client.py, line 53 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGjdHR0yIQM9H5YMU:-K8bGjdHR0yIQM9H5YMV:1005992995) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/ssh_client.py#L53)):*
So, all of these (and the actual map), I'm not sure where the best place to put them would be.  Does anyone have some insight on what the "python-y" way to do this would be (keep as static methods or move out of the class).  Thanks!

---

*[ufo/ssh_client.py, line 88 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGy10tDfWkdDlI2nl:-K8bGy10tDfWkdDlI2nm:-1591267300) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/ssh_client.py#L88)):*
I'd really like to use enums and class pointers here, not really sure how though...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-:-K8bFMLfxmNz5oKKQcms:1042377518)*

**Comment by jpevarnek** [comment]
@xwsxethan @blueandgold can PTAL, thanks :)

**Comment by blueandgold** [comment]
Looks great overall to me.  Just a couple of small comments, which I hope might help.

---

Review status: 1 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[ufo/models.py, line 112 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bFW7p9yXvGNC_v9sO:-K8tyAr4jQ83CAVC69so:1102900746) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/models.py#L112)):*
No issues.  I think it's fine.

---

*[ufo/models.py, line 125 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bFnNkEjiHMAPU7iX3:-K8u-BN42EUvveIdnDKv:-1504533077) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/models.py#L125)):*
Purely by looking at the hostkeys documentation, how about using the add() of the HostKeys class?  No guarantee if this will work fo you, as I am not exactly sure if "contents" is the same "key" that's expected in the method signature.

http://pydoc.net/Python/paramiko/1.9.0/paramiko.hostkeys/

---

*[ufo/proxy_server.py, line 42 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bG-uW5db9hv0Qlfiz:-K8u1VGQaWP8ZL1xtbJ0:1556310326) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/proxy_server.py#L42)):*
It's clean by me.  :)  The only thing I can think of is maybe extract the private key operations into a separate method, convert_private_key_to_text().

 return {
    "id": server.id,
    "name": server.name,
    "ip_address": server.ip_address,
    "public_key": public_key.get_name() + ' ' + public_key.get_base64(),
    "private_key": convert_private_key_to_text(),
    }

---

*[ufo/proxy_server.py, line 86 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGSv3bMF-T9FxxGC4:-K8tyWn-gk40_26uu19c:1114015000) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/proxy_server.py#L86)):*
Can we add a TODO, so that we will remember to do this later?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-:-K8u2MXY7LnOq6pWEwJa:-890943121)*

**Comment by xwsxethan** [comment]
Same, looks good to me, just a few nits. :+1: 

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[ufo/ssh_client.py, line 77 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8u4zE-U5EfzJ4DsMNC:-K8u4zE0ezLEFLnwN36y:-498946192) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/ssh_client.py#L77)):*
You seem to be mixing single and double quotes in this file. I think in general we're using single quotes throughout, so that is probably best, but if you want to do double quotes then that is fine as well, so long as it is consistent.

---

*[ufo/ssh_client.py, line 88 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGy10tDfWkdDlI2nl:-K8u5OfAQg3Il3ZYl2QJ:-652622871) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/ssh_client.py#L88)):*
For the key type strings, it would be nice if they are constants that are referenced throughout at least.

As far as making them enums and class pointers, that would be great, but I'm with you on the "not sure how that works in python" front. To my understanding, base python 2.7 did not even support it without using pypi or a similar package that ports it in. I'm sure you could roll something yourself, but that seems like overkill.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-:-K8u6lBt9lz3yQ_KnLVO:-1942220296)*

**Comment by jpevarnek** [comment]
Review status: 4 of 6 files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[ufo/models.py, line 125 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bFnNkEjiHMAPU7iX3:-K8uFCmjNO0Alkgv9t-I:1416476601) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/models.py#L125)):*
Contents will probably consist of `keytype base64(key) other_stuff` depending on how the user copied it.  That method unfortunately would not help at all with what we want to do (which is really):

```
type = figure_out_type_from_line(contents)
if type == 'ssh-rsa':
  key = RSAKey(b64decode(get_key(contents)))
elif type == 'ssh-dss':
  ...
```

`from_line` is the only thing I found in Paramiko that did anything remotely similar to that.  We very easily could just handle splitting that line and assuming whatever entry is after one of the tags we are looking for is a valid base64-encode hostkey.  Not quite as good as parsing it through this, but it would work...  I'm just not sure whether that is worth writing.

---

*[ufo/proxy_server.py, line 42 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bG-uW5db9hv0Qlfiz:-K8uGS9Sk1dbrlC8UZZR:-371923613) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/proxy_server.py#L42)):*
Hmm, maybe having something like that in the actual model (e.g. `server.get_private_key_text()`) and maybe even moving some automatic calls there for `public_key_data_to_object`...  I really have no idea what I like better here, it all seems so mangled together.

---

*[ufo/proxy_server.py, line 67 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGLPoPvDlnc2-VC89:-K8uHMx6TiJKsWKCC4c_:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/proxy_server.py#L67)):*
Done.

---

*[ufo/proxy_server.py, line 86 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGSv3bMF-T9FxxGC4:-K8uGzgByTckM2xZQHBh:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/proxy_server.py#L86)):*
Done.

---

*[ufo/ssh_client.py, line 13 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGf5thuUmGWCpiaCs:-K8uHznyn_r2lboho8RW:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/ssh_client.py#L13)):*
Done.

---

*[ufo/ssh_client.py, line 77 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8u4zE-U5EfzJ4DsMNC:-K8uI8lNgURVITgz0ep4:966175663) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/ssh_client.py#L77)):*
Done. (double quotes kept for docstrings)

---

*[ufo/ssh_client.py, line 88 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8bGy10tDfWkdDlI2nl:-K8uVYIXHSTVWB5aHeuI:735953547) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/493eb3508a2441d80856a82da5289b1c67914f34/ufo/ssh_client.py#L88)):*
Switched to constants, does that look good to you?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16)*

**Comment by xwsxethan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16)*

**Comment by blueandgold** [comment]
Nice work here, can't wait to try this out!  :lgtm: 

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-:-K8udVLY9IiO5k5xyCYe:1882963190)*

**Comment by jpevarnek** [comment]
Ahh, okay, last changes, I promise.  This is just updating the tests.

**Comment by xwsxethan** [comment]
Just a bunch of random nits, but looks great.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 13 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8yQkyjZFmiHZX4LC95:-K8yQkykDedgIn53_eDf:1119522418) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L13)):*
Nit: Punctuation and can probably fit on one line.

---

*[ufo/proxy_server_test.py, line 52 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8yRHyHfy5Sk6BTBDPm:-K8yRHyHfy5Sk6BTBDPn:68444265) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L52)):*
Why did you switch this to for i instead of for each? It looks like it still could be done with for each. It doesn't really matter, but I'm more curious.

---

*[ufo/proxy_server_test.py, line 89 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8yRr8CFUP9nxB5YqbD:-K8yRr8CFUP9nxB5YqbE:1086087620) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L89)):*
Nit: No docstring

---

*[ufo/proxy_server_test.py, line 129 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8yS87KNtArCFu6w9l7:-K8yS87KNtArCFu6w9l8:1086087620) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L129)):*
Nit: No docstring

---

*[ufo/proxy_server_test.py, line 141 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8ySJWmK_04uSPlP6md:-K8ySJWmK_04uSPlP6me:1086087620) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L141)):*
Nit: No docstring

---

*[ufo/proxy_server_test.py, line 150 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8ySMSTZE1ozIlXnej8:-K8ySMSTZE1ozIlXnej9:1086087620) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L150)):*
Nit: No docstring

---

*[ufo/proxy_server_test.py, line 155 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8ySm8s_cQXyjy9tO-K:-K8ySm8s_cQXyjy9tO-L:-197104315) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L155)):*
Nit: Spacing. If you're going for the 4 space hanging indent, then I guess that's acceptable, but I'm not sure why since server_id could be aligned with 'proxyserver_delete'. Thought you were doing objective C for a second, and I did one of these: http://i.imgur.com/vIaqV8R.gif. This is also in the testDeleteProxyServerRemovesFromDb method.

---

*[ufo/proxy_server_test.py, line 158 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8ySg9Ef8sZO5IR_aa9:-K8ySg9Ef8sZO5IR_aaA:1086087620) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L158)):*
Nit: No docstring

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-:-K8yU5h9Ad7VLLM_9MYa:-1777744228)*

**Comment by blueandgold** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 52 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8yRHyHfy5Sk6BTBDPm:-K8z4wEpwR5Pgpij5ehG:-1947927740) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L52)):*
nit: can drop the "proxy_server" assignment in the above statement, i.e. just invoke:
`self._CreateAndSaveFakeProxyServer(i)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16)*

**Comment by jpevarnek** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 13 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8yQkyjZFmiHZX4LC95:-K92d_ImkiVAhsp_Rv4s:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L13)):*
Done.

---

*[ufo/proxy_server_test.py, line 52 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8yRHyHfy5Sk6BTBDPm:-K92djwuFcNuQhY4pHYg:2035894650) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L52)):*
Switching to just iterating over the range was done because the actual value is not really relevant here.  Doing it with actually iteration would have been `for i, _ in enumerate(FAKE_PROXY_SERVER_DATA)` with `_` being totally ignored.  Just going over the values seemed easier.

---

*[ufo/proxy_server_test.py, line 89 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8yRr8CFUP9nxB5YqbD:-K92gQjMhj1GGiJJlrBz:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L89)):*
Done.

---

*[ufo/proxy_server_test.py, line 129 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8yS87KNtArCFu6w9l7:-K92gEfJPrwQx20wolzx:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L129)):*
Done.

---

*[ufo/proxy_server_test.py, line 141 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8ySJWmK_04uSPlP6md:-K92gFB0t26NN4OLi8Ra:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L141)):*
Done.

---

*[ufo/proxy_server_test.py, line 150 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8ySMSTZE1ozIlXnej8:-K92gFqbeWhnl5yHIclz:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L150)):*
Done.

---

*[ufo/proxy_server_test.py, line 155 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8ySm8s_cQXyjy9tO-K:-K92fp5hkPDe-iRvnbuS:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L155)):*
Done.

---

*[ufo/proxy_server_test.py, line 158 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16#-K8ySg9Ef8sZO5IR_aa9:-K92frBGujDjmZyPvmlN:71861590) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cb0b0948e90733ec6a5883b5fb858a5d3961862f/ufo/proxy_server_test.py#L158)):*
Leaving without a docstring, private and trivial method with self-explanatory name.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/16)*

**Comment by blueandgold** [comment]
:+1:

**Pull request merged**
