### PR TITLE
Implementing the Expand Functionality for the List UI of Users and Servers

### PR DESCRIPTION
**Pull request by xwsxethan**
Pretty straightforward actually, just a little JS. Currently the limit is 10.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/47)

### CODE REVIEW

**Comment by xwsxethan** [comment]
Pics or it didn't happen:
ufoexpandui01
ufoexpandui02

**Comment by blueandgold** [comment]
Cool, just one nit.  I think we will integrate our PRs better if you submit this first, and then mine next.  :+1: 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[ufo/static/listItems.html, line 48 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/47#-KBOmSowx_T3BaIx0ff9:-KBOmSoxPUs5tUROx7Mi:-416530472) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1ff827640315f2af3c44a8824c0117235e9b9b4b/ufo/static/listItems.html#L48)):*
nit: maybe the name can be better as "_hasMoretoShow", since it is boolean result and should follow the boolean naming convention.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/47#-:-KBOmmi_oIAvuVzJN-UM:-1593859680)*

**Comment by xwsxethan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[ufo/static/listItems.html, line 48 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/47#-KBOmSowx_T3BaIx0ff9:-KBPIz-3_h5Cs1WcmEFq:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/1ff827640315f2af3c44a8824c0117235e9b9b4b/ufo/static/listItems.html#L48)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/47)*

**Comment by xwsxethan** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/47)*

**Pull request merged**
