### PR TITLE
A general error handler to gracefully catch (nearly) all application errors

### PR DESCRIPTION
**Pull request by blueandgold**
- The goal here is to have a mechanism to gracefully catch (nearly) all the application errors.
- Other specifics, e.g. how exactly to handle the errors, are TBD, pending UX mocks (i.e. html, butterbars, polymer toasts, etc).
- The work here is based on the guide at https://goo.gl/OWOa70, but improved to allow custom exceptions to be handled.
- Added a custom SetupNeeded error, thus making /not_setup/ routing to be unnecessary.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/21)

### CODE REVIEW

**Comment by blueandgold** [comment]
@jpevarnek to take a look as well, hope the tests are what you expect.  :)

**Comment by xwsxethan** [comment]
Looks good to me. I had a couple of nits on indentation and a few questions just about how things work, but seems like a great step. :+1: pending the nits are fixed.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[ufo/error_handler.py, line 23 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K8yMZwvFGsXn5yshGVY:-K8yMZwvFGsXn5yshGVZ:544448070) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e8d3cc9ee35da12d4fe8fed90070683289d65fc1/ufo/error_handler.py#L23)):*
Nit: Indent

---

*[ufo/error_handler.py, line 28 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K8yLQxGsfLzLw0WIPs9:-K8yLQxGsfLzLw0WIPsA:-838463291) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e8d3cc9ee35da12d4fe8fed90070683289d65fc1/ufo/error_handler.py#L28)):*
Just a question here, will this go to the same logging service used elsewhere (in proxy server and setup I believe)? Also, what is the difference between flask.current_app and ufo.app? I just wanna make sure we're being consistent in our references.

---

*[ufo/error_handler.py, line 37 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K8yMmRykE8zY9OBVGjA:-K8yMmRykE8zY9OBVGjB:-1823783369) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e8d3cc9ee35da12d4fe8fed90070683289d65fc1/ufo/error_handler.py#L37)):*
Another general question, but for both @jpevarnek and @blueandgold : what is the convention for i18n and exceptions? Do we translate them as appropriate or leave them as is? Do we translate everything or just some pieces? I would expect we keep '500 Internal Server Error' untranslated and translate whatever the message is if it is a custom error, otherwise keep it untranslated. This implementation looks fine by the way, but I wanted to get an opinion from you two on the i18n portion while I had it on my mind.

---

*[ufo/error_handler.py, line 44 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K8yMID7aqGuTmOw_VWP:-K8yMID7aqGuTmOw_VWQ:1471927256) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e8d3cc9ee35da12d4fe8fed90070683289d65fc1/ufo/error_handler.py#L44)):*
Nit: This can probably fit on one line (and I think the comment above can be fit on fewer as well, but I'll leave that to you).

---

*[ufo/error_handler.py, line 52 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K8yMbLY2SwYicd4gvlQ:-K8yMbLY2SwYicd4gvlR:544448070) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e8d3cc9ee35da12d4fe8fed90070683289d65fc1/ufo/error_handler.py#L52)):*
Nit: Indent

---

*[ufo/error_handler_test.py, line 28 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K8yMcT5krIsqRgn0FiU:-K8yMcT5krIsqRgn0FiV:544448070) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e8d3cc9ee35da12d4fe8fed90070683289d65fc1/ufo/error_handler_test.py#L28)):*
Nit: Indent

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-:-K8yNr25RTb5kR3T4SBJ:-1873615470)*

**Comment by xwsxethan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21)*

**Comment by xwsxethan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21)*

**Comment by xwsxethan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21)*

**Comment by xwsxethan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21)*

**Comment by blueandgold** [comment]
Having issue with Ethan's comment on reviewable, so will follow up on them here.

- All nits are done.

- Good question on the logging.  I actually don't know whether the difference between request-context logging vs app-context logging, mainly how these logs are collected on Heroku.  I'll change this back to request logging (as elsewhere) and the person working on logging functionality can decide.

- For i18n, I would first think that our target users are admin-types.  So, they would be able to understand standard terminologies like "Not Found", "Bad Request", "Internal Server Error", etc, which I don't think we should translate.  What would be nice to translate for them are custom messages like 'Please finish configuring this site' or "Our server is encountering difficulties at the moment.  Please come back and try again in a few minutes."

**Comment by jpevarnek** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[ufo/error_handler.py, line 17 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92i370Xat_VVqYAm7i:-K92i370Xat_VVqYAm7j:-393110489) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L17)):*
I love avoiding magic numbers as much as the next guy, but when the number is actually in your variable name, it serves no purpose.

---

*[ufo/error_handler.py, line 33 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92k7n-nYfduLByGzMv:-K92k7n-nYfduLByGzMw:-282750288) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L33)):*
I think we'd be better off just going with `error.description` here.  `get_description` seems to wrap the text in an html tag e don't want.

---

*[ufo/error_handler.py, line 35 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92i0eG4Y8vYjy77MiN:-K92i0eH-nRYRPBZ-ndT:795066623) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L35)):*
Suggestion: Instead of this conditional block, just add an if statement for:
```
if not isInstance(error, HTTPException):
  error = exceptions.InternalServerError(error.message)
```

we'll reduce a code path, get rid of a couple constants, and I think simplify things overall.

---

*[ufo/error_handler.py, line 47 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92kttOTN1mZDVGOXoR:-K92kttOTN1mZDVGOXoS:-1511582158) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L47)):*
I think this will be addressed by the comment a couple up, but I don't think we should be passing text we did not explicitly generate to `Markup` considering its purpose is to get rid of escaping.

---

*[ufo/error_handler.py, line 56 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92h_M36Th1JQNtJJO2:-K92h_M36Th1JQNtJJO3:-2067122896) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L56)):*
This is one of the places I would *really* like to see us importing by module so I'm able to get the context of precisely where this variable is coming from.

---

*[ufo/error_handler_test.py, line 9 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92lE_4FWCUV2DopuK9:-K92lE_4FWCUV2DopuKA:-538682551) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler_test.py#L9)):*
Again, think it would be useful to import the modules in this case.

---

*[ufo/error_handler_test.py, line 27 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92lY41bQOAzmRPYE_g:-K92lY42hYXOsL56Tx0p:-1955959564) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler_test.py#L27)):*
I think this would be better described as "Test unknown exception types are handled" or something like that.

Also, not important right now, but I think we'd rather give them a nicer error than a 500 page (And, actually, would go farther and claim that this counts as either 200 or 400.  Definitely not 5xx as the server is able to process everything fine and probably not 4xx because there is nothing wrong with that specific request, but that's open for debate I think)

---

*[ufo/error_handler_test.py, line 30 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92m0foCTPBEamFilB-:-K92m0foCTPBEamFilB0:1422244793) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler_test.py#L30)):*
I'd say leave it here, this is looking at error handling and not one of the methods in the `setup` path

---

*[ufo/setup.py, line 11 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92mdQJ8tUobe3M3g7v:-K92mdQJ8tUobe3M3g7w:-923696056) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/setup.py#L11)):*
Just double-checking, we're fine that there will be no context if whoever raises this passes a message into the constructor?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21)*

**Comment by blueandgold** [comment]
Thanks for the review!! PTAL

---

Review status: 1 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[ufo/error_handler.py, line 17 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92i370Xat_VVqYAm7i:-K93VE5uzGKicqkZzBcf:-628945590) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L17)):*
Done.  Just removed entirely per the other of your comment.

---

*[ufo/error_handler.py, line 33 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92k7n-nYfduLByGzMv:-K93W7hvhJYTa_Awas6W:1706342937) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L33)):*
Done. 

---

*[ufo/error_handler.py, line 35 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92i0eG4Y8vYjy77MiN:-K93jzLfAKlz37p_w5_o:1493156513) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L35)):*
This is a great idea!  Everything is indeed cleaner.  Done.

---

*[ufo/error_handler.py, line 47 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92kttOTN1mZDVGOXoR:-K93k3zBpirnwwhbjmV_:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L47)):*
Done.

---

*[ufo/error_handler.py, line 56 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92h_M36Th1JQNtJJO2:-K93kILpdrDn-vOzM_AK:936283537) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler.py#L56)):*
Done.  Made this change everywhere (within the scope of this CL).

---

*[ufo/error_handler_test.py, line 9 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92lE_4FWCUV2DopuK9:-K93lC0PDfmTABNd9tym:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler_test.py#L9)):*
Done.

---

*[ufo/error_handler_test.py, line 27 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92lY41bQOAzmRPYE_g:-K93mn0SrHJDwIQaLoNR:-1042427345) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler_test.py#L27)):*
Done.  Changed the name.

No real preference here, but we do have to wrap the unknown exceptions in a specific werkzeug http exception.  And 500 was just the one seems to fit the best overall.

---

*[ufo/error_handler_test.py, line 30 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92m0foCTPBEamFilB-:-K93lETDBj8zf8GVWx_h:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/error_handler_test.py#L30)):*
Done.

---

*[ufo/setup.py, line 11 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K92mdQJ8tUobe3M3g7v:-K93lTyJqHh2hUK1tNJC:-1389279720) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/cc5e6dcef94de2bea60498caf80ca3483d7118db/ufo/setup.py#L11)):*
I think it's okay for now because it's only thrown from one very specific place.  It's always easy to change later if this error class is re-used in other places.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-:-K93nsDcmuvpcdnGAUNJ:115072863)*

**Comment by jpevarnek** [comment]
:thumbsup: with comment at your discretion

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ufo/error_handler.py, line 12 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K98x-oP4GD31cKhPIJL:-K98x-oP4GD31cKhPIJM:-982946647) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/9c8f60960ac6822394261a23c6d95ee353b9f8b8/ufo/error_handler.py#L12)):*
Might simplify things to do `from werkzeug import exceptions`, your call though

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-:-K98xLJ0QcCwG_aq_La1:-1853749532)*

**Comment by blueandgold** [comment]
Thanks for the review!

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[ufo/error_handler.py, line 12 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-K98x-oP4GD31cKhPIJL:-K9973ltp5705t88yAy9:1007480884) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/9c8f60960ac6822394261a23c6d95ee353b9f8b8/ufo/error_handler.py#L12)):*
Done.  The other way would provide more context since there's a couple of different exceptions now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/21#-:-K997MF64Dbe1teBAv58:-588504495)*

**Pull request merged**
