### PR TITLE
Recaptcha

### PR DESCRIPTION
**Pull request by xwsxethan**
Second pass at this following: https://github.com/uProxy/ufo-management-server-flask/pull/150

Please review this carefully and let me know what you think. I've tried to document what is happening in the code fairly thoroughly, but I'm happy to add more as necessary. Thanks!

---

This change is [Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/154)

### CODE REVIEW

**Comment by blueandgold** [comment]
Nice work overall.  The code is really clean, but I have some comments on organization.

Just a note, I am not able to login even being verified by recaptcha.  I tried about 3 or 4 times on the prod instance.  Each time, I am verified, but still can not login.

After trying this out, yes, I see how this is not testable by webdriver.  Guess this is something we will definitely want to test manually for sure.

<details><summary><i>Previously, xwsxethan (Ethan) wrote…</i></summary>
> #### Recaptcha
> 
> Second pass at this following: https://github.com/uProxy/ufo-management-server-flask/pull/150
> 
> 
> 
> Please review this carefully and let me know what you think. I've tried to document what is happening in the code fairly thoroughly, but I'm happy to add more as necessary. Thanks!
> 
> 
> 
</details>


---

Review status: 0 of 13 files reviewed at latest revision, 12 unresolved discussions.

---

*[config.py, line 23 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe-_ygEUYceP83ZxuH:-KIe-_ygEUYceP83ZxuI:-706341207) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/config.py#L23)):*
> ```Python
>   SHARED_OAUTH_CLIENT_SECRET = 'R5H27t1C-9enMO9ZNfxym3Gw'
>   WHOOSH_BASE = 'sqlite:///' + os.path.join(app.instance_path, 'search.db')
>   RECAPTCHA_SITE_KEY = '6LcGsiATAAAAAMzn-dtA9_73dPktkof7bDUIZxtK'
> ```

Hmmm, should we consider for this to be configured via the UI?  Otherwise, I'm concerned about people opening up this file to edit, and break something, which is easy to do, not to mention not too user-friendly.  Okay to put a TODO.

Also, we should not check this value in directly?

---

*[migrations/versions/e773f9b8d47e_.py, line 1 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIdyFIi2GT_xfhEvL40:-KIdyFIi2GT_xfhEvL41:-1082106365) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/migrations/versions/e773f9b8d47e_.py#L1)):*
> ```Python
> """empty message
> ```

Does this file need to be checked in?

---

*[ufo/__init__.py, line 25 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe1JdV_tL9W3qWeQ1u:-KIe1JdW7lSVfI4M8e3Z:-617086495) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/__init__.py#L25)):*
> ```Python
>   app.config['WHOOSH_BASE'] = os.environ['DATABASE_URL']
> 
> if 'RECAPTCHA_SECRET_KEY' in os.environ:
> ```

qq: what would happen if the secret key is not configured or present?

---

*[ufo/database/models.py, line 165 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIdyalHKrFCizubRqRJ:-KIdyalI-xDSkpoucoa-:1998085717) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/database/models.py#L165)):*
> ```Python
>   user_undelete_action = ufo.db.Column(ufo.db.String(LONG_STRING_LENGTH),
>                                        default=CRON_JOB_ACTIONS['nothing'])
>   show_recaptcha = ufo.db.Column(ufo.db.Boolean(), default=False)
> ```

nit: boolean naming please
```should_show_recaptcha```

---

*[ufo/database/models.py, line 191 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe0_jZFnCv9mREZH-6:-KIe0_jZFnCv9mREZH-7:-698345238) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/database/models.py#L191)):*
> ```Python
>   id = ufo.db.Column(ufo.db.Integer, primary_key=True)
> 
>   occurred = ufo.db.Column(ufo.db.DateTime())
> ```

nit: append suffix "_datetime" to be consistent with above?
```occurred_datetime```

---

*[ufo/handlers/auth.py, line 152 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIeJNWBf-ta0CU1DGYQ:-KIeJNWCMslfkbyAUM2N:1164506790) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/auth.py#L152)):*
> ```Python
>   now = datetime.datetime.now()
> 
>   if config.show_recaptcha:
> ```

I hate to ask, but the execution flow in this if-if-elif-else-if block really deserves some unit testing.

```python
testTurnOffRecaptchaIfRecaptchaWasOnAndTimedOut()
testTurnOnRecaptchaIfRecaptchaWasOnAndFailedAttemptsAreGreaterThanMax()
testTurnOnRecaptchaIfRecaptchaWasOffAndFailedAttemptsAreGreaterThanMax()
```

Possibly, for easier testing, extract this whole block out into a separate method, and make them return.  This would somewhat break up the nested conditions and easier to assert.
Maybe something like:
```python

def DetermineIfRecaptchaShouldBeTurnedOnOrOff(failed_login_attemps, config, etc...):
   if config.show_recaptcha:
    failed_attempts_count = _count_failed_logins_since_datetime(
        failed_login_attempts, config.recaptcha_start_datetime)

    if config.recaptcha_end_datetime < now:
      # This is the case when the recaptcha was on and timed out so turn it off
      config.show_recaptcha = False
      _purge_old_failed_login_attempts(
          failed_login_attempts, config.recaptcha_end_datetime)
      return config, failed_attempts_count
  
    if failed_attempts_count >= MAX_FAILED_LOGINS_BEFORE_RECAPTCHA:
      # This is the case when the recaptcha was on and has since seen more
      # failures over the threshold, so it needs to be extended.
      delta = (
          config.recaptcha_end_datetime - config.recaptcha_start_datetime)
      _turn_on_recaptcha(config, now, delta * 2)
      return config, failed_attempts_count

  delta = datetime.timedelta(minutes=INITIAL_RECAPTCHA_TIMEFRAME_MINUTES)
  failed_attempts_count = _count_failed_logins_since_datetime(
      failed_login_attempts, now - delta)
  if failed_attempts_count >= MAX_FAILED_LOGINS_BEFORE_RECAPTCHA:
    # This is the case when I need to turn on recaptcha initially.
    _turn_on_recaptcha(config, now, delta)
  return config, failed_attempts_count

```

---

*[ufo/handlers/auth.py, line 181 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIeG6wdNGrzgMUwkDAD:-KIeG6weCRxVHSf8O6ht:1465459084) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/auth.py#L181)):*
> ```Python
>                                error=flask.request.form.get('error'))
> 
> def _create_new_failed_login():
> ```

This should be a database api, and not be here.

---

*[ufo/handlers/auth.py, line 211 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIeI46dXxrMEQSLs406:-KIeI46dXxrMEQSLs407:-945429030) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/auth.py#L211)):*
> ```Python
>   """
>   recent_failures = 0
>   for attempt in failed_login_attempts:
> ```

This would also be better as a database api, especially if we can use a query to retrieve the failed_login_attempts.

---

*[ufo/handlers/auth.py, line 216 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIeIi8OyogFEPN2iNGY:-KIeIi8Plsw3fKkTWbgF:1861506650) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/auth.py#L216)):*
> ```Python
>   return recent_failures
> 
> def _purge_old_failed_login_attempts(failed_login_attempts, previous_datetime):
> ```

Also would be better as database api.
Maybe call this:
```_purge_expired_failed_login_attempts```

---

*[ufo/handlers/setup.py, line 120 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIdzuZhAfzqy-c7WSgf:-KIdzuZhAfzqy-c7WSgg:-1529481845) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/setup.py#L120)):*
> ```Python
> 
>   config.isConfigured = True
>   config.show_recaptcha = False
> ```

nit: boolean naming
```config.should_show_recaptcha```

---

*[ufo/static/loginForm.html, line 52 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe-5L_s-kZzR-qH2PS:-KIe-5LauFbrZEDRnW9V:-989519943) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/static/loginForm.html#L52)):*
> ```HTML
>           type: Number,
>         },
>         showRecaptcha: {
> ```

nit: boolean naming
```shouldShowRecaptcha```

---

*[ufo/templates/login.html, line 10 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe2iVllWglIJrjZe2r:-KIe2iVmZ6HQeqtJ1r09:1491666885) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/templates/login.html#L10)):*
> ```HTML
>   <paper-display-template resources="{{login_resources}}">
>     <header-container resources="{{login_resources}}">
>       {% if session['show_recaptcha'] %}
> ```

boolean naming

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-:-KIdxaJarS3ovmxHTtGh:1747251216)*

**Comment by blueandgold** [comment]
Filling in some comments that went missing because of bad markup.

<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> Nice work overall.  The code is really clean, but I have some comments on organization.
> 
> Just a note, I am not able to login even being verified by recaptcha.  I tried about 3 or 4 times on the prod instance.  Each time, I am verified, but still can not login.
> 
> After trying this out, yes, I see how this is not testable by webdriver.  Guess this is something we will definitely want to test manually for sure.
</details>


---

Review status: 0 of 13 files reviewed at latest revision, 12 unresolved discussions.

---

*[ufo/database/models.py, line 165 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIdyalHKrFCizubRqRJ:-KIeOsRDvnWgOcWKv0Qx:138305144) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/database/models.py#L165)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> nit: boolean naming please
> ```should_show_recaptcha```
</details>
```
should_show_recaptcha
```

---

*[ufo/handlers/setup.py, line 120 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIdzuZhAfzqy-c7WSgf:-KIeOyhGy5Bpb_fsoYC6:1233692746) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/setup.py#L120)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> nit: boolean naming
> ```config.should_show_recaptcha```
</details>
```
config.should_show_recaptcha
```

---

*[ufo/static/loginForm.html, line 52 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe-5L_s-kZzR-qH2PS:-KIeP4_T_RgOQDuieqZm:-1136692994) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/static/loginForm.html#L52)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> nit: boolean naming
> ```shouldShowRecaptcha```
</details>
```
shouldShowRecaptcha
```

---

*[ufo/templates/login.html, line 10 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe2iVllWglIJrjZe2r:-KIePBdJhDXRycpFGilw:138305144) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/templates/login.html#L10)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> boolean naming
</details>
```
should_show_recaptcha
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-:-KIePHDTzzBK6p1X5eo0:-1633970946)*

**Comment by xwsxethan** [comment]
I can still login after triggering recaptcha, so that's odd. Were you using the new credentials I sent you?

<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> Filling in some comments that went missing because of bad markup.
</details>


---

Reviewed 13 of 13 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[config.py, line 23 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe-_ygEUYceP83ZxuH:-KIhTPYin_cNaDnRKzKU:1836117848) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/config.py#L23)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> Hmmm, should we consider for this to be configured via the UI?  Otherwise, I'm concerned about people opening up this file to edit, and break something, which is easy to do, not to mention not too user-friendly.  Okay to put a TODO.
> 
> Also, we should not check this value in directly?
</details>
I think this value is okay to leave here since it is actually the public key. This gets rendered in the UI every time anyway. The real one to keep secret is the secret key, which gets pulled in from a local environment variable (which I've already configured on our standing instances). I can move this on out to an environment variable as well, but again, it will show up in the html on the client every time, so it isn't very secret.

---

*[migrations/versions/e773f9b8d47e_.py, line 1 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIdyFIi2GT_xfhEvL40:-KIhTp_3gyECvDtJPjzi:-2011113345) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/migrations/versions/e773f9b8d47e_.py#L1)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> Does this file need to be checked in?
</details>
Yes, now that this is fixed, this is the migration from the previous DB state to the new one. It is only necessary for the current standing instances. Any instances spun up afterwards won't require a migration.

---

*[ufo/__init__.py, line 25 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe1JdV_tL9W3qWeQ1u:-KIhUxt2kG_KRxOSIt2W:784350101) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/__init__.py#L25)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> qq: what would happen if the secret key is not configured or present?
</details>
I think recaptcha will just fail to verify, blocking the user from logging in. I added a logging statement though so there is at least some record of this happening.

---

*[ufo/database/models.py, line 165 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIdyalHKrFCizubRqRJ:-KIhVosIe-e5DijRiwH9:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/database/models.py#L165)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> ```
> should_show_recaptcha
> ```
</details>
Done.

---

*[ufo/database/models.py, line 191 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe0_jZFnCv9mREZH-6:-KIhWsOcNOe3k2ngHh85:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/database/models.py#L191)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> nit: append suffix "_datetime" to be consistent with above?
> ```occurred_datetime```
> 
</details>
Done.

---

*[ufo/handlers/auth.py, line 152 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIeJNWBf-ta0CU1DGYQ:-KIhnWyh7y7a76eNK-AF:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/auth.py#L152)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> I hate to ask, but the execution flow in this if-if-elif-else-if block really deserves some unit testing.
> 
> ```python
> testTurnOffRecaptchaIfRecaptchaWasOnAndTimedOut()
> testTurnOnRecaptchaIfRecaptchaWasOnAndFailedAttemptsAreGreaterThanMax()
> testTurnOnRecaptchaIfRecaptchaWasOffAndFailedAttemptsAreGreaterThanMax()
> ```
> 
> Possibly, for easier testing, extract this whole block out into a separate method, and make them return.  This would somewhat break up the nested conditions and easier to assert.
> Maybe something like:
> ```python
> 
> def DetermineIfRecaptchaShouldBeTurnedOnOrOff(failed_login_attemps, config, etc...):
>    if config.show_recaptcha:
>     failed_attempts_count = _count_failed_logins_since_datetime(
>         failed_login_attempts, config.recaptcha_start_datetime)
> 
>     if config.recaptcha_end_datetime < now:
>       # This is the case when the recaptcha was on and timed out so turn it off
>       config.show_recaptcha = False
>       _purge_old_failed_login_attempts(
>           failed_login_attempts, config.recaptcha_end_datetime)
>       return config, failed_attempts_count
>   
>     if failed_attempts_count >= MAX_FAILED_LOGINS_BEFORE_RECAPTCHA:
>       # This is the case when the recaptcha was on and has since seen more
>       # failures over the threshold, so it needs to be extended.
>       delta = (
>           config.recaptcha_end_datetime - config.recaptcha_start_datetime)
>       _turn_on_recaptcha(config, now, delta * 2)
>       return config, failed_attempts_count
> 
>   delta = datetime.timedelta(minutes=INITIAL_RECAPTCHA_TIMEFRAME_MINUTES)
>   failed_attempts_count = _count_failed_logins_since_datetime(
>       failed_login_attempts, now - delta)
>   if failed_attempts_count >= MAX_FAILED_LOGINS_BEFORE_RECAPTCHA:
>     # This is the case when I need to turn on recaptcha initially.
>     _turn_on_recaptcha(config, now, delta)
>   return config, failed_attempts_count
> 
> ```
</details>
Done.

---

*[ufo/handlers/auth.py, line 181 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIeG6wdNGrzgMUwkDAD:-KIhZ1T_83ca77UWD-CN:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/auth.py#L181)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> This should be a database api, and not be here.
</details>
Done.

---

*[ufo/handlers/auth.py, line 211 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIeI46dXxrMEQSLs406:-KIhd3CKUAp3Pxw8XZNC:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/auth.py#L211)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> This would also be better as a database api, especially if we can use a query to retrieve the failed_login_attempts.
</details>
Done.

---

*[ufo/handlers/auth.py, line 216 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIeIi8OyogFEPN2iNGY:-KIhdLqvcOdvQhW1IJwc:1234860417) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/auth.py#L216)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> Also would be better as database api.
> Maybe call this:
> ```_purge_expired_failed_login_attempts```
</details>
The name didn't exactly come through in this comment, but done.

---

*[ufo/handlers/setup.py, line 120 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIdzuZhAfzqy-c7WSgf:-KIhWMY7T6c9O3yUySsZ:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/handlers/setup.py#L120)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> ```
> config.should_show_recaptcha
> ```
</details>
Done.

---

*[ufo/static/loginForm.html, line 52 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe-5L_s-kZzR-qH2PS:-KIhWY2AADhcxkE3h1A7:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/static/loginForm.html#L52)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> ```
> shouldShowRecaptcha
> ```
</details>
Done.

---

*[ufo/templates/login.html, line 10 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIe2iVllWglIJrjZe2r:-KIhWIEFBoTPf-I-QB7W:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/206224720aadc9623f1d1c72b0b5bd45d63fec68/ufo/templates/login.html#L10)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> ```
> should_show_recaptcha
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-:-KIhTCjSCPb5QIatlry_:-1483301034)*

**Comment by blueandgold** [comment]
+1 Looks really good to me.  Love all the testing in place now.

I also think that there is benefit to have a webdriver test to assert that the recaptca actually turns on.  This can be setup at the end of the webdriver test suite, so that it's the last test to run.  Then at that point, someone can manually login to verify the recaptcha validation works.  Okay to put as a TODO.

Yes, I can test why I couldn't sign in again after you merge this and I pull it.  But I think I was doing everything I was suppose to do.

<details><summary><i>Previously, xwsxethan (Ethan) wrote…</i></summary>
> I can still login after triggering recaptcha, so that's odd. Were you using the new credentials I sent you?
</details>


---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[ufo/handlers/auth_test.py, line 103 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIhxHzdrFoPSD7DpYwd:-KIhxHzdrFoPSD7DpYwe:-893308171) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/f19c61a797b23969573b9b5f7df92b59d721dea3/ufo/handlers/auth_test.py#L103)):*
> ```Python
>         minutes=auth.INITIAL_RECAPTCHA_TIMEFRAME_MINUTES)
>     self.assertEquals(default_delta, new_delta)
> ```

nit: remove extra line here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-:-KIhxTfmjyl6nESGNlLD:-1971033304)*

**Comment by xwsxethan** [comment]
Sounds good. The only thing I would be worried about is using that web driver test on the master version or having to ever run tests back to back. At that point you have to wait at least the 2 minute threshold for it to go away (assuming no one else triggers it up to the threshold again afterwards). I've added a TODO though.

<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> +1 Looks really good to me.  Love all the testing in place now.
> 
> I also think that there is benefit to have a webdriver test to assert that the recaptca actually turns on.  This can be setup at the end of the webdriver test suite, so that it's the last test to run.  Then at that point, someone can manually login to verify the recaptcha validation works.  Okay to put as a TODO.
> 
> Yes, I can test why I couldn't sign in again after you merge this and I pull it.  But I think I was doing everything I was suppose to do.
</details>


---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[ufo/handlers/auth_test.py, line 103 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-KIhxHzdrFoPSD7DpYwd:-KIi3GyytqIimXUEIvUU:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/f19c61a797b23969573b9b5f7df92b59d721dea3/ufo/handlers/auth_test.py#L103)):*
<details><summary><i>Previously, blueandgold (Henry Chang) wrote…</i></summary>
> nit: remove extra line here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/154#-:-KIi3PL-VuDm6SXRIgmE:-572942146)*

**Pull request merged**
