### PR TITLE
Migrate the proxy server tests.

### PR DESCRIPTION
**Pull request by blueandgold**
This is based on user_test.py.  But there are some improvements, such as better testing of the edit post handler.  I will also go back to user_test.py to improve it after this.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/18)

### CODE REVIEW

**Comment by blueandgold** [comment]
@jpevarnek to take a look too

**Comment by xwsxethan** [comment]
I had a couple of random nits, but the structure and asserts look fine to me! :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 11 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI8yW75IeLP8DfJax:-K8aI8yW75IeLP8DfJay:1986532805) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L11)):*
You probably don't need a lot of this. I've been slowly cleaning it up in my tests, but you should be able to get rid of each of the following imports:
import os
from flask.ext.testing import TestCase
import json
from . import app
from . import db

as well as the BASE_DIR constant.

---

*[ufo/proxy_server_test.py, line 103 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI7KDrs62qe7aHxaV:-K8aI7KDrs62qe7aHxaW:544448070) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L103)):*
Nit: Indent

---

*[ufo/proxy_server_test.py, line 144 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI6Mqn7dDS1bMzd0O:-K8aI6Mqn7dDS1bMzd0P:544448070) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L144)):*
Nit: Indent

---

*[ufo/proxy_server_test.py, line 159 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI3q95tjSZM2IU8T2:-K8aI3q95tjSZM2IU8T3:544448070) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L159)):*
Nit: Indent

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-:-K8aIbAXCmQ-3MHUVHFU:-514887674)*

**Comment by goldspin** [comment]
Thanks for the review!

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 11 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI8yW75IeLP8DfJax:-K8aKhWVFmyho5E04Y5d:-808317335) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L11)):*
Done, great tip.  But still need the os.

---

*[ufo/proxy_server_test.py, line 103 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI7KDrs62qe7aHxaV:-K8aKrxZasZ7Nutp5bcv:-436985573) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L103)):*
Done.  Is travis catching this, or something it can do?

---

*[ufo/proxy_server_test.py, line 144 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI6Mqn7dDS1bMzd0O:-K8aL1QNzkf7UJgL5IOf:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L144)):*
Done.

---

*[ufo/proxy_server_test.py, line 159 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI3q95tjSZM2IU8T2:-K8aL5y4KyvXStOtLPM2:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L159)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-:-K8aLUyQKyQxCrR1LGP5:-588504495)*

**Comment by xwsxethan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 11 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI8yW75IeLP8DfJax:-K8aLtLphdIHWZD6UYgg:-471303435) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L11)):*
Out of curiosity, what for? I was able to remove it in mine without an issue once the BASE_DIR constant was removed.

---

*[ufo/proxy_server_test.py, line 103 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI7KDrs62qe7aHxaV:-K8aM0pWggHBVb-M1EN5:1410228846) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L103)):*
Hmmm, I'm not sure. Landscape would catch it, but it has been acting up recently. I've been trying to track the progress, but basically some things went haywire, and the sole developer on the project got in a car accident, so he has been unable to fix things and get it back up and running lately. If it continues to be a problem then I'll start looking into another tool to monitor code health and general lint errors.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18)*

**Comment by goldspin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 11 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8aI8yW75IeLP8DfJax:-K8aP670oZi2JH0gSOH6:-1451562991) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/6b5cdb94d8888613528aeab10d67286233fb6038/ufo/proxy_server_test.py#L11)):*
Done.  Removing os this time works!  Maybe I was looking at the wrong errors.  Thanks for following up on this.  :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18)*

**Comment by jpevarnek** [comment]
I've tried to only mention things once as I saw them, sorry if I repeated myself a bit.  In general, just a couple comments on the scope of unit testing, and it looks like we use the model in a few places we do not have to, but otherwise looks good.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 53 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8atrZkgmKzV-1kYl9K:-K8atrZkgmKzV-1kYl9L:801078916) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L53)):*
Same question as usual, not sure what this is actually testing.

---

*[ufo/proxy_server_test.py, line 65 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8atznBgAhO2ASAKlAB:-K8atznBgAhO2ASAKlAC:226569979) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L65)):*
This is testing that an arbitrary id we chose is in the response data for a specific route, I'm honestly not sure here what kind of errors we want to catch.

---

*[ufo/proxy_server_test.py, line 69 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8auLBy0MTqYcU5XY5L:-K8auLBy0MTqYcU5XY5M:-1894767940) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L69)):*
I'd feel a lot better if we got the data directly from the test data instead of first initializing a real model here.

---

*[ufo/proxy_server_test.py, line 81 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8auVBwXDFiwHYG5G9n:-K8auVBwXDFiwHYG5G9o:-860571570) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L81)):*
Hardcoded id should not be necessary.

---

*[ufo/proxy_server_test.py, line 91 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8b64FhkZBCu5WHK5Qk:-K8b64FhkZBCu5WHK5Ql:-1516496583) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L91)):*
Should be a separate test

To expand a bit more on the conversation we had earlier today:

The idea with a unit test should be that we are looking at a single piece of functionality in the code.  In this case, I'd ever say `testAddProxyServer` might be a better name as it asserts that the proxy server gets added by the test.  Having another test, `testRedirectsToListAfterAddingServer` (I suck at naming stuff, can you tell) that checks the redirect would be useful as well, but I don't think it makes sense here.

go/unit-test-practices#behavior-testing seems to expand upon this a bit

---

*[ufo/proxy_server_test.py, line 98 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8b6z3qXCUoXi5E3h_P:-K8b6z3qXCUoXi5E3h_Q:460483125) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L98)):*
I'd feel a LOT better if we were not relying on hardcoded IDs in the data we create.

---

*[ufo/proxy_server_test.py, line 139 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8b6-X9I3UDrnqvXhxu:-K8b6-X9I3UDrnqvXhxv:-1186924005) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L139)):*
Should be a separate test

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-:-K8b7GiW0FAaJcaW2JpG:-1284492036)*

**Comment by blueandgold** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 53 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8atrZkgmKzV-1kYl9K:-K8eM9mHbE850UERa95B:-561560454) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L53)):*
This is to verify that the list page is actually gotten.  i.e. asserting on a couple of text elements on list page.  Dropping them, and I am open to any other suggestions.

---

*[ufo/proxy_server_test.py, line 65 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8atznBgAhO2ASAKlAB:-K8eN0RzdHQjeL26sz4u:-673348782) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L65)):*
Changed to asserting on the route will render the appropriate html.

---

*[ufo/proxy_server_test.py, line 69 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8auLBy0MTqYcU5XY5L:-K8eSCNYabfI4TqbS6PE:-91686990) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L69)):*
Done.  Was doing it just to make things a bit cleaner.

---

*[ufo/proxy_server_test.py, line 81 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8auVBwXDFiwHYG5G9n:-K8eUHNaDe0bd9f7ekmu:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L81)):*
Done.

---

*[ufo/proxy_server_test.py, line 91 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8b64FhkZBCu5WHK5Qk:-K8eVogRYFL_xwKIobCP:-884242997) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L91)):*
That's a great link for behavioral testing, thanks!  But I think it makes more sense to keep the redirect assert here because it's on the same code execution path.  For a counter example, the get parameter triggers a different execution flow, thus deserving to have a separate test (which we do have).  Also, this is what the user_test.py is also doing.

Changed the name.  But it breaks the pattern of names that's already in place.

---

*[ufo/proxy_server_test.py, line 98 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8b6z3qXCUoXi5E3h_P:-K8eXPmFt2XH9Afvj1N2:-717841714) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L98)):*
In this case, I'm not sure I understand why using the pre-defined ID is not so hot.  But I went ahead to retrieve it back from the db.

---

*[ufo/proxy_server_test.py, line 139 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8b6-X9I3UDrnqvXhxu:-K8eYuRtjD8IltegWDB4:510123539) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L139)):*
As mentioned above, this is on the same code execution path, so it makes sense to keep it here and test this right away after saving.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18)*

**Comment by jpevarnek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 53 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8atrZkgmKzV-1kYl9K:-K8ehHkkCnnFeWKqTFhy:-871662849) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L53)):*
I think just checking that the expected template is actually the one that got rendered would handle this fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18)*

**Comment by blueandgold** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 53 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8atrZkgmKzV-1kYl9K:-K8frkD_xkHelJ42-tE9:-700098902) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L53)):*
Thanks for the review.  Done.  To me, this seems only possible by mocking the render_template(), and check its call history.  So, I'm doing this separately in a new test method:
testListHandlerRendersTheListTemplate()

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18)*

**Comment by jpevarnek** [comment]
No further comments, :thumbsup: at your discretion

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ufo/proxy_server_test.py, line 91 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8b64FhkZBCu5WHK5Qk:-K8kLs2IcJm8GrDwJiKL:2074522744) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L91)):*
Okay, fine with leaving it here for now, I'm still going to assert for unit tests that we should not be having the single test be responsible for too much, even if it is on the same code execution path.  If something breaks, I'd love to be able to tell exactly what is wrong from which test failed.

---

*[ufo/proxy_server_test.py, line 98 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-K8b6z3qXCUoXi5E3h_P:-K8kLkc2Yo7l2qPAsEAZ:-1762417661) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/458187a1ca25e0d909363021c89aa2fe2f1621f6/ufo/proxy_server_test.py#L98)):*
It's not that it's *that* bad, it just does not seem necessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-:-K8kMKSSdJR1mP7XggNC:-370867338)*

**Comment by blueandgold** [comment]
Thanks for the review!  Will merge this now.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/18#-:-K8tqjN-p0cRTpz3WYlL:-1570273835)*

**Pull request merged**
