### PR TITLE
Add simple user authentication

### PR DESCRIPTION
**Pull request by jpevarnek**
This adds the ability to specify a username and password for an admin
user when setting up the server and to check that the user is logged in
on all pages.

We should add another page to allow the user to change the password or
to add additional users, that's outside the scope of this PR.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/33)

### CODE REVIEW

**Comment by xwsxethan** [comment]
Overall, it looks good to me. The comments I have were mostly docstring and import nits. Would you mind adding some sort of test for logging in at the setup handler if possible? Also, the current tests don't pass, so that should be fixed obviously.

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks broke.

---

*[ufo/auth.py, line 1 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAeywktj1mWiZcBQvh3:-KAeywktj1mWiZcBQvh4:968785807) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L1)):*
Nit: module docstring

---

*[ufo/auth.py, line 8 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAeyzjupwO_-tgXXPoK:-KAeyzjupwO_-tgXXPoL:-1020741017) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L8)):*
Nit: class docstring

---

*[ufo/auth.py, line 12 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAez08Oat7z5EdB3VBt:-KAez08Oat7z5EdB3VBu:-784785541) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L12)):*
Nit: function docstring

---

*[ufo/auth.py, line 21 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAez3AcmpTOVTPKSc6p:-KAez3AcmpTOVTPKSc6q:-621562175) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L21)):*
Nit: args, returns, and raises sections in docstring, also for decorated function

---

*[ufo/auth.py, line 33 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAezF6K2ZYEUc2_Wokv:-KAezF6K2ZYEUc2_Wokw:-621562175) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L33)):*
Nit: args, returns, and raises sections in docstring, also for decorated function

---

*[ufo/auth.py, line 46 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAezMWWAtEEJGWmtxlJ:-KAezMWWAtEEJGWmtxlK:-48162784) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L46)):*
Nit: returns section in docstring

---

*[ufo/auth.py, line 69 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAez_MvqwyGZ90XKBhj:-KAez_MvqwyGZ90XKBhk:600615978) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L69)):*
If you add a TODO for this, I'll go ahead and implement cleaning up the logout action in the sidebar (or potentially just moving it) in another PR.

---

*[ufo/auth.py, line 70 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAezWiEqvxk6fuP_XzD:-KAezWiEqvxk6fuP_XzE:-48162784) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L70)):*
Nit: returns section in docstring

---

*[ufo/base_test.py, line 21 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf-Tx3S0zL9oCHPwrn:-KAf-Tx3S0zL9oCHPwro:-784785541) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/base_test.py#L21)):*
Nit: function docstring

---

*[ufo/error_handler.py, line 34 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf-FEUrAFxdu7r8G-N:-KAf-FEUrAFxdu7r8G-O:-1516084606) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/error_handler.py#L34)):*
Should add a test for this at some point, but I'm fine with leaving that as a TODO.

---

*[ufo/models.py, line 1 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf-b_62UcMJJEM2big:-KAf-b_62UcMJJEM2bih:1007465488) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/models.py#L1)):*
Import should be from ufo import db. I realize you didn't necessarily write this, but would be easy to go ahead and clean up now.

---

*[ufo/models.py, line 159 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf-XG-ozO4b5A7Qj7u:-KAf-XG-ozO4b5A7Qj7v:-784785541) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/models.py#L159)):*
Nit: function docstring

---

*[ufo/models.py, line 162 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf-ZQbF3Tq1nSC-6Gw:-KAf-ZQbF3Tq1nSC-6Gx:-784785541) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/models.py#L162)):*
Nit: function docstring

---

*[ufo/models.py, line 165 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf-ojYkBaS2qp3hTPC:-KAf-ojYkBaS2qp3hTPD:-784785541) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/models.py#L165)):*
Nit: function docstring

---

*[ufo/proxy_server.py, line 3 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf-v8aHg8llMHI3EMK:-KAf-v8aHg8llMHI3EML:-1304893476) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/proxy_server.py#L3)):*
Nit: Imports should be from ufo import foo. I realize you didn't necessarily write this, but would be easy to go ahead and clean up now if you do not mind.

---

*[ufo/setup.py, line 1 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf03_2b7VY9bPPW0-0:-KAf03_2b7VY9bPPW0-1:-1304893476) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/setup.py#L1)):*
Nit: Imports should be from ufo import foo. I realize you didn't necessarily write this, but would be easy to go ahead and clean up now if you do not mind.

---

*[ufo/setup.py, line 19 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf064cw9PIi8_rZiNc:-KAf064cw9PIi8_rZiNd:-1020741017) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/setup.py#L19)):*
Nit: class docstring

---

*[ufo/setup.py, line 27 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf09JseNOVKOkIC4SE:-KAf09JseNOVKOkIC4SF:-48162784) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/setup.py#L27)):*
Nit: returns section in docstring

---

*[ufo/setup.py, line 88 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf0buYNOcuG-tYu08-:-KAf0buYNOcuG-tYu080:2132387479) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/setup.py#L88)):*
Should add at least 1 test for this.

---

*[ufo/user.py, line 1 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf0sLN_ZE1DuS9X5mc:-KAf0sLN_ZE1DuS9X5md:-1304893476) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/user.py#L1)):*
Nit: Imports should be from ufo import foo. I realize you didn't necessarily write this, but would be easy to go ahead and clean up now if you do not mind.

---

*[ufo/user.py, line 8 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf0jeN89PAnsXxv_wq:-KAf0jeON5zr5DlR0H_9:-390648141) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/user.py#L8)):*
Nit: ufo imports should be in a separate section after the others (I think, but if I'm wrong on this then my apologies).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-:-KAf136BWzknsIYCNqqU:163966298)*

**Comment by blueandgold** [comment]
Great work!  Just a couple of style nits.

---

Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks broke.

---

*[ufo/auth.py, line 37 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf9GU3C6lRE_S3GUgy:-KAf9GU3C6lRE_S3GUgz:-1472407120) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L37)):*
nit: I think the logic here would be easier to follow if we can breakdown the conditions a bit.  Such as:

`
if not config.isConfigured:
  return f(*args, **kwargs)

if not is_user_logged_in():
  raise NotLoggedIn
`

---

*[ufo/auth.py, line 58 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf9ytV8YwSyQE9QYt-:-KAf9ytV8YwSyQE9QYt0:-1883934768) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L58)):*
nit: since check_password is returning a boolean, this line would read better as:
`if not user.is_valid_password(password):`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-:-KAfCzoZXaVlZD6YeLvi:486990945)*

**Comment by blueandgold** [comment]
Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks broke.

---

*[ufo/auth.py, line 37 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf9GU3C6lRE_S3GUgy:-KAfDAz91CdjfpnLrucS:-241285183) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/auth.py#L37)):*
Sorry, this might work better.

`
if not config.isConfigured:
return f(args, *kwargs)

if is_user_logged_in():
return f(args, *kwargs)

raise NotLoggedIn
`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33)*

**Comment by xwsxethan** [comment]
Took care of my own nits here, going to follow up on Henry's shortly.

---

Reviewed 27 of 34 files at r2.
Review status: 17 of 23 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-:-KD9L_NK5dXpMsb-o0iv:516754535)*

**Comment by xwsxethan** [comment]
Reviewed 1 of 34 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ufo/handlers/auth.py, line 37 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf9GU3C6lRE_S3GUgy:-KD9N-eSqv-RMiUb2ipZ:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/handlers/auth.py#L37)):*
Done.

---

*[ufo/handlers/auth.py, line 58 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KAf9ytV8YwSyQE9QYt-:-KD9N1UGOhSM_SX5fdjq:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/8f78f60aad0d72616c18a4e457936a1f10533fb5/ufo/handlers/auth.py#L58)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33)*

**Comment by xwsxethan** [comment]
Just an extra note, when running this locally, you're going to have to rerun `pip install -r requirements.txt` to pick up the bcrypt library. When doing so in my own environment, I had a problem with it compiling bcrypt and cffi. To fix that, I had to run the following to pickup libffi (see here https://community.letsencrypt.org/t/insecureplatformwarning-failed-building-wheel-for-cryptography-cffi/5657):

`sudo apt-get install build-essential libssl-dev libffi-dev python-dev`

**Comment by blueandgold** [comment]
Thanks for pushing this to the finish line!  Some nits below, but I would also like to see more test coverage for this, since the login is so critical: 

- verify that a user who is not logged in, will not be access the landing page, the setup page, etc.
- when a user tries to login with incorrect password (the app won't let them through)
- unit tests for auth.py: does_password_match(), set_password(), etc.

It's okay to put TODOs and follow-up.  :lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[ufo/database/models.py, line 303 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KD9ZjcnWS6YHKCHF77P:-KD9ZjcnWS6YHKCHF77Q:1173697972) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/f59ebd49257280b195d8bc85baf56230d38b1e01/ufo/database/models.py#L303)):*
nit: Can this be more simply called as "AdminUser"?

---

*[ufo/handlers/auth.py, line 10 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KD9ZP9_s777B9Dj_78J:-KD9ZP9_s777B9Dj_78K:2127554292) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/f59ebd49257280b195d8bc85baf56230d38b1e01/ufo/handlers/auth.py#L10)):*
nit: Can we move this to the services/custom_exceptions.py module?  Then, you can just add an import without changing how this is used here.
```python
from ufo.services.custom_exceptions import NotLoggedIn
```

---

*[ufo/handlers/proxy_server.py, line 74 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KD9b1P6IQvtN60fWhsw:-KD9b1P7GrGBzII0l_Re:864319242) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/f59ebd49257280b195d8bc85baf56230d38b1e01/ufo/handlers/proxy_server.py#L74)):*
I just want to double-check here: @auth.login_required would guard against a nake post (i.e. a post by someone who is not logged in), correct?  Look at auth.py, it would check if there is a username in flask session.  That is okay?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-:-KD9becI84lz4aNuN_Lk:2083947978)*

**Comment by xwsxethan** [comment]
Reviewed 1 of 34 files at r2, 4 of 4 files at r4, 2 of 4 files at r5.
Review status: 24 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[ufo/database/models.py, line 303 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KD9ZjcnWS6YHKCHF77P:-KD9hRnnCcN2-ujeTjfe:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/f59ebd49257280b195d8bc85baf56230d38b1e01/ufo/database/models.py#L303)):*
Done.

---

*[ufo/handlers/auth.py, line 10 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KD9ZP9_s777B9Dj_78J:-KD9iESFoRXxXgBuPc9r:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/f59ebd49257280b195d8bc85baf56230d38b1e01/ufo/handlers/auth.py#L10)):*
Done.

---

*[ufo/handlers/proxy_server.py, line 74 \[r3\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-KD9b1P6IQvtN60fWhsw:-KD9hmj7yxe78sSNMOcj:966208014) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/f59ebd49257280b195d8bc85baf56230d38b1e01/ufo/handlers/proxy_server.py#L74)):*
That question is better for @jpevarnek , but I assume it is okay. It is currently checking that the username is in the session and that the username is in fact valid (hasn't been deleted somehow).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33)*

**Comment by xwsxethan** [comment]
Reviewed 1 of 34 files at r2, 2 of 4 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33)*

**Comment by blueandgold** [comment]
:lgtm: for the newer changes

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/33#-:-KD9mXJstHJEurqQMSq7:1910676187)*

**Pull request merged**
