### PR TITLE
New UI for the oauth configuration.

### PR DESCRIPTION
**Pull request by blueandgold**
The changes here are:
- Focus on the proper code structure of the new UI first.  Will work on actually polishing the UI later.
- Making the oauth configuration into a custom element.  This makes the setup page so much cleaner.
- Added polymer template conditionals to display the proper text, which previously was done in jinja.
- Added to_dict() for the config model, so that we can pass them into the custom element.  I will refactor this into a separate method later.
- There is currently the following error, which I think is due to xsrf.  Basically, the server is throwing this, even before processing anything else.  Have you seen something similar for the other pages?

```
403 - Forbidden
You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
```

[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/52)

### CODE REVIEW

**Comment by xwsxethan** [comment]
The xsrf issue is probably because it is trying to generate one in Jinja on the page, which won't work anymore. Basically, since the Polymer elements aren't bound until load on the client end, Jinja won't get executed in the handler, but rather when flask is trying to serve up a raw file for vulcanized.html (since that's where custom elements live until being bound).

The way I've overcome this is to place a single xsrf token into a hidden element on the base page that everything inherits from, which will execute Jinja during a request. Check some of the other custom elements to see how I get the value out then reuse in whatever form as necessary, like the example below:

 <input type="hidden" name="_xsrf_token" value="{{getXsrfToken()}}">
...
getXsrfToken: function() {
        return document.getElementById('globalXsrf').value;
      },

**Comment by xwsxethan** [comment]
I'll check the rest tomorrow morning if that's alright, but I wanted to go ahead and pass the xsrf bit along if that was blocking you.

**Comment by xwsxethan** [comment]
:lgtm: Just a few spacing nits and one TODO, so feel free to submit after those. Nicely done!

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ufo/database/models.py, line 68 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-KBmo80ltVi4UdUWc_d2:-KBmo80mxUA33YtUO5HB:1099296581) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/3e9912dc911278a0df1d4e5edbf958bd7d231149/ufo/database/models.py#L68)):*
Nit: spacing.

---

*[ufo/handlers/setup.py, line 51 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-KBmoPGQUp3DNUP2Ohdv:-KBmoPGQUp3DNUP2Ohdw:1099296581) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/3e9912dc911278a0df1d4e5edbf958bd7d231149/ufo/handlers/setup.py#L51)):*
Nit: spacing.

---

*[ufo/static/oauthConfiguration.html, line 11 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-KBmogPkRCE0biI15exw:-KBmogPkRCE0biI15exx:2050761376) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/3e9912dc911278a0df1d4e5edbf958bd7d231149/ufo/static/oauthConfiguration.html#L11)):*
I won't make you actually pull all these strings out yourself, but can you leave a TODO here so I know to follow up with it for i18n eventually?

---

*[ufo/static/oauthConfiguration.html, line 25 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-KBmoW4ilFZyIroTNpHp:-KBmoW4ilFZyIroTNpHq:286120844) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/3e9912dc911278a0df1d4e5edbf958bd7d231149/ufo/static/oauthConfiguration.html#L25)):*
Nit: spacing at end of line.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-:-KBmouQH-hdWkgFamWd-:1268302717)*

**Comment by blueandgold** [comment]
Thanks for the review!  So, that explains what's happening with the xsrf.  But I actually found the globalXsrf token actually being generated in landing2.html.  I'm not sure that's the right "base", so leaving it as a TODO to fix later.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ufo/database/models.py, line 68 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-KBmo80ltVi4UdUWc_d2:-KBnJyXSPQLGDbNQl8Uc:-1500788794) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/3e9912dc911278a0df1d4e5edbf958bd7d231149/ufo/database/models.py#L68)):*
Weird, only reviewable will display the extra whitespaces, but not in regular github view of the file.  Just want to say that I did try to catch these before and not make anyone having to manually spot these.  :(

---

*[ufo/handlers/setup.py, line 51 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-KBmoPGQUp3DNUP2Ohdv:-KBnKUx2xDYAd_fR929F:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/3e9912dc911278a0df1d4e5edbf958bd7d231149/ufo/handlers/setup.py#L51)):*
Done.

---

*[ufo/static/oauthConfiguration.html, line 11 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-KBmogPkRCE0biI15exw:-KBnKnw05HntmchK5eY-:1492519718) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/3e9912dc911278a0df1d4e5edbf958bd7d231149/ufo/static/oauthConfiguration.html#L11)):*
Done.  And cool.  I think it's better to wait until we actually get to the i18n before extracting these.  Then, we can also get a better sense of where and how to structure the strings.

---

*[ufo/static/oauthConfiguration.html, line 25 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-KBmoW4ilFZyIroTNpHp:-KBnLBiF_CQfNnvhxuuv:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/3e9912dc911278a0df1d4e5edbf958bd7d231149/ufo/static/oauthConfiguration.html#L25)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-:-KBnLLb6XegLwbodUt_N:1834999107)*

**Comment by xwsxethan** [comment]
Oh, that's right, I did put it in the landing page. Yeah, that should probably be in base so that every page gets it. Just leave that as a TODO though, and I'll fix it in a PR sometime. :+1: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ufo/database/models.py, line 68 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-KBmo80ltVi4UdUWc_d2:-KBnMWQDeTgijOSza2y3:-1264957965) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/3e9912dc911278a0df1d4e5edbf958bd7d231149/ufo/database/models.py#L68)):*
Hey it's fine, there was only like two so no big deal. You can probably configure your editor to spot these for you though and auto-remove them. That's what I have sublime do. Not sure what you're using, but I'm sure there's some setting for it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-:-KBnMG3tEUTxEj1P9Yiv:1362124721)*

**Comment by blueandgold** [comment]
I use eclipse on my office box.  I'm sure eclipse can do it, I'll fiddle with it.  Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/52#-:-KBnNquTqmBG3eppJ6uI:858380278)*

**Pull request merged**
