### PR TITLE
REDO: Cron Job for User Sync with Directory Service

### PR DESCRIPTION
**Pull request by xwsxethan**
I initially did this work in a separate PR which got accidentally blended with some vulcanization. The initial one was #40, which is now closed. You can view the progress there as well as the finished product here.

This includes basic support for configurations, although the configurations are not yet user facing (so we rely on defaults at the moment). The work to implement those configurations in a user facing way will be a separate PR as part of the overall move to the new UI. This does not have a functional test yet, though it likely needs one.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/41)

### CODE REVIEW

**Comment by blueandgold** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[clock.py, line 22 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnRqXHiR94KlFB_Vsk:-KBnRqXIiTygN2eHhBYp:1523425189) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/clock.py#L22)):*
This is being very nit-picky, but can we avoid using "cron" here?  Because more accurately, we are spinning up a standalone clock process (as opposed to something like cron that runs on every machine).  See the doc description [here] (https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes).

```
Cron has been used historically, but is ill-suited for horizontally scalable environments such as Heroku. A more powerful, flexible solution is a clock process.

A clock process uses the process model to run a lightweight singleton process that wakes up at a specified interval and schedules the work to be performed. 
```

---

*[clock.py, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnTWbFICgHnQHU2MHq:-KBnTWbFICgHnQHU2MHr:2147441782) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/clock.py#L24)):*
Do you think that we should pull out the user sync code out of the handler code into a separate module in the service directory?  So, this line would become like below:

```python
ufo.service.enqueue_user_sync()
```

---

*[ufo/handlers/user.py, line 346 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnWXynhGjd_QxpwXkn:-KBnWXyoY38_ib1uGEgL:1377584049) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L346)):*
The comparison operator should be != instead.

```python
if db_user_domain != config.domain:
```
This SO answer has a good explaination why:
http://stackoverflow.com/a/2209781/2830207

---

*[ufo/handlers/user.py, line 347 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnWgJ3gYx75A3NdnWA:-KBnWgJ3gYx75A3NdnWB:-1650054340) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L347)):*
Should we at least log something should this come up?  (since we are checking for this condition)

---

*[ufo/handlers/user.py, line 350 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnYwKF3QzRLuy4wj6P:-KBnYwKGsBudwvEiCFN4:-1222042082) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L350)):*
With the nested loops here, the runtime would be N^2, right?  Can we make this better, such as get a dict of users from the directory service , e.g. with the email as key.  So this will boil down to one loop of the db_users.  And yes, to get this dict of users would require a new method in google_directory_service.py.

Not super-critical now, so okay to leave it as a TODO.  But I think that large enterprises will benefit from this.

---

*[ufo/handlers/user.py, line 351 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnXxYiobibvPICaMR1:-KBnXxYiobibvPICaMR2:-1509322943) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L351)):*
nit: as above, == should be used here for testing equality

---

*[ufo/handlers/user.py, line 355 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnXaECPnhX2LHbcOon:-KBnXaECPnhX2LHbcOoo:67079535) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L355)):*
nit: Can we make the naming more clear, such as "is_found_in_directory"?  So this line can read clearly as:
```python
if not is_found_in_directory:
```

---

*[ufo/handlers/user.py, line 360 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnVoa7S3cvPgl73iKE:-KBnVoa7S3cvPgl73iKF:1863817366) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L360)):*
It's usually recommended to make try/except to be as targeted as possible.  In this case, how about something like below, note the return in the except clause.

```python
 try:
    directory_service = google_directory_service.GoogleDirectoryService(
        credentials)
    directory_users = directory_service.GetUsers()
except errors.HttpError as error:
    ufo.app.logger.info('Error encountered while requesting users from '
                        'directory service: ' + str(error))
    return

<rest of code.....>
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41)*

**Comment by xwsxethan** [comment]
Sorry for the long delay in my response; it took forever to get this thing to test and work correctly. The scheduling process was working, but then it would silently fail. Anyway, it is working now, and I think I've addressed all previous comments. Please take another look @blueandgold 

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[clock.py, line 22 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnRqXHiR94KlFB_Vsk:-KBne3EuJ0VAlM12U8iJ:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/clock.py#L22)):*
Done.

---

*[clock.py, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnTWbFICgHnQHU2MHq:-KBne53CLMj6E4xHukXV:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/clock.py#L24)):*
Done.

---

*[ufo/handlers/user.py, line 346 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnWXynhGjd_QxpwXkn:-KBneAZkwtVwucj-qRlK:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L346)):*
Done.

---

*[ufo/handlers/user.py, line 347 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnWgJ3gYx75A3NdnWA:-KBnbkHyRbN0SEUHaxt0:1863787794) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L347)):*
This condition is for when a user was added manually or with a previous domain which is no longer configured. I'm not sure how often this will actually come up, but I've added the logging so we'll have some trace now. Done.

---

*[ufo/handlers/user.py, line 350 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnYwKF3QzRLuy4wj6P:-KBni87xMzRjr_jbjvxW:-1586400673) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L350)):*
Yeah sure, it's done. The run time for this new approach will be O(N + M) where N is the amount of users in our database (since we check each) and M is the amount of users in the domain (as we have to write the entire list of domain users into a dictionary for quick lookup).

---

*[ufo/handlers/user.py, line 351 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnXxYiobibvPICaMR1:-KBneC3QmVBVtnB9LHB1:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L351)):*
Done.

---

*[ufo/handlers/user.py, line 355 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnXaECPnhX2LHbcOon:-KBni_kMl7A-jxjq11fG:277069704) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L355)):*
I actually removed the found boolean entirely since it is no longer necessary with immediate lookup. So done-ish.

---

*[ufo/handlers/user.py, line 360 \[r1\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBnVoa7S3cvPgl73iKE:-KBnihgqk72DmdrTnAiI:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/021b6ae7ab74915e487a0b30f4cb37bea8e4dca8/ufo/handlers/user.py#L360)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-:-KBoBJ6yD7lVnSBhC3QK:2110035617)*

**Comment by blueandgold** [comment]
Looks really good now!  Some nits and a TODO for unit test before merging.  :lgtm:  :+1: 

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[ufo/services/user_sync.py, line 12 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoFErzZHJh67XqWlJB:-KBoFErzZHJh67XqWlJC:136238582) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L12)):*
nit: Looking at this class name, maybe a cooler name would be UserSynchronizer? (more java-esque, at least)  If you do that, then this module would also be user_synchronizer.py.  Totally up to you.

---

*[ufo/services/user_sync.py, line 15 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoIrKUroHs8luT8Vav:-KBoIrKUroHs8luT8Vaw:-1584182205) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L15)):*
This is really nit-picking as well: This method does more than just checking, so the naming should be reflected appropriately.  How about change "check" to "sync":

```python
def _sync_db_users_against_directory_service(self):
```

---

*[ufo/services/user_sync.py, line 54 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoGLqNEnNK80ytSYdq:-KBoGLqNEnNK80ytSYdr:-1241147472) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L54)):*
==  instead of is

---

*[ufo/services/user_sync.py, line 58 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoGQc-SaEy8PFoTWbq:-KBoGQc-SaEy8PFoTWbr:-1241147472) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L58)):*
==  instead of is

---

*[ufo/services/user_sync.py, line 66 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoJfR2XXv-Iqzp1Zog:-KBoJfR2XXv-Iqzp1Zoh:600699579) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L66)):*
There is a bunch of nested conditions which I think are worth unit testing.  Okay not to do it in this PR as a lot of time has been spent here.  But please put a TODO to follow-up for later.

---

*[ufo/services/user_sync.py, line 67 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoIORqdBU7g6eczY2s:-KBoIORqdBU7g6eczY2t:-1241147472) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L67)):*
==  instead of is

---

*[ufo/services/user_sync.py, line 71 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoIP8-nSU9Q4e9XvTz:-KBoIP8-nSU9Q4e9XvU-:-1241147472) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L71)):*
==  instead of is

---

*[ufo/services/user_sync.py, line 75 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoHn5hlVF5K1J0GzVy:-KBoHn5i0TGxyWeBso_Y:-1583666863) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L75)):*
Just out of curiosity, what is the purpose of tracking whether or not a user is revoked by cron?

---

*[ufo/services/user_sync.py, line 81 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoFYgWQ3v_mN_BEPkA:-KBoFYgX84e5bbvQNVFg:-1021627380) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L81)):*
nit: the trailing """" should be on the previous line.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-:-KBoKAw-smZutUF7AQGA:-1327418985)*

**Comment by xwsxethan** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[ufo/services/user_sync.py, line 12 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoFErzZHJh67XqWlJB:-KBoM2c6hQwYw2SSINwz:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L12)):*
Done.

---

*[ufo/services/user_sync.py, line 15 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoIrKUroHs8luT8Vav:-KBoM7ztiTMNeXZ78RTu:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L15)):*
Done.

---

*[ufo/services/user_sync.py, line 54 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoGLqNEnNK80ytSYdq:-KBoMC_yD5_dEPG7A2NB:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L54)):*
Done.

---

*[ufo/services/user_sync.py, line 58 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoGQc-SaEy8PFoTWbq:-KBoMDHvdytwE9uGb4Ds:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L58)):*
Done.

---

*[ufo/services/user_sync.py, line 66 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoJfR2XXv-Iqzp1Zog:-KBoMjWTY-3iiusuVo-y:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L66)):*
Done.

---

*[ufo/services/user_sync.py, line 67 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoIORqdBU7g6eczY2s:-KBoMkw-kcGGgX21ohxk:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L67)):*
Done.

---

*[ufo/services/user_sync.py, line 71 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoIP8-nSU9Q4e9XvTz:-KBoMmYaOGv_Lx8XQQQj:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L71)):*
Done.

---

*[ufo/services/user_sync.py, line 75 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoHn5hlVF5K1J0GzVy:-KBoMobdCKi2nhOVLG0n:-1365570978) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L75)):*
At the moment, we don't do anything with it, but we could conceivably turn on the feature I was suggesting in the design doc where we monitor whether the user has been un-revoked. In which case we would want to then un-revoke the user if that user was revoked by cron, but not if the user was manually revoked. I just went ahead and made the DB change now so we don't have to update schema multiple times since it is kind of a pain. Same reason for the unrevoked and undeleted settings in config, though neither is currently used.

---

*[ufo/services/user_sync.py, line 81 \[r2\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41#-KBoFYgWQ3v_mN_BEPkA:-KBoNM00ovfGDXW85WuU:1769256090) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/e7c402ceebca014f8d5ffdfa9aa1605be9ea19d2/ufo/services/user_sync.py#L81)):*
Nice catch! I had to move this when at one point everything was further indented, which made it go over the 80 character limit. Fits again now so I moved back. Thanks, done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/41)*

**Pull request merged**
