### PR TITLE
Starting a PR for Updating to the New UI, See Pics in Comments

### PR DESCRIPTION
**Pull request by xwsxethan**
First attempt at new UI layout. Still need more cards/material for the server and to fix various colors, but this is a start. I hate CSS... soooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo much.

This is obviously not ready yet, but please feel free to comment. Polymer css is being a pain, but I'm trying to use that rather than directly specifying padding, margins, ect.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/44)

### CODE REVIEW

**Comment by xwsxethan** [comment]
ufonewui

**Comment by xwsxethan** [comment]
Better UI version:
ufonewui02

**Comment by xwsxethan** [comment]
Separated the new page out to a new handler and added json handler for ajax requests of users. The UI didn't change that much here, but there was a lot of plumbing going on to make things work correctly. Need to update tests, but currently I have forked this off entirely so the existing tests should pass.
ufonewui03

**Comment by xwsxethan** [comment]
ufonewui04

**Comment by blueandgold** [comment]
Looks great overall...!  I just have a few comments about changing the structure of things a bit, which I think can make things simpler to read & maintain.  Let me know how you think!

---

Review status: 0 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[ufo/proxy_server.py, line 38 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFVGIpNx9h_CgYiz72:-KBFVGIpNx9h_CgYiz73:-1581991568) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/proxy_server.py#L38)):*
Please see my similar comment below about possibly moving this to the database side.
i.e. GetProxyServersAsDict()

---

*[ufo/static/getItemsAjaxIntoList.html, line 1 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFWF1ZJ06gb6oaD2aM:-KBFWF1ZJ06gb6oaD2aN:1843106809) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/static/getItemsAjaxIntoList.html#L1)):*
Is there anything that would be worth having unit test?  For example, is the correct button displayed when the appropriate attribute is passed in?  i.e. user vs proxy server?

These seem like good references, particularly the first one:
(1) https://medium.com/google-developer-experts/polymer-unit-testing-d6a69910dc31#.bhuw3rw7u
(2) https://www.polymer-project.org/0.5/articles/unit-testing-elements.html

---

*[ufo/static/getItemsAjaxIntoList.html, line 50 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFQSQZ7MoCvW_eixsC:-KBFQSQZ7MoCvW_eixsD:-626311356) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/static/getItemsAjaxIntoList.html#L50)):*
nit: Maybe it's just the way that I'm looking at this, but do you think these conditionals would be simpler if we have something like:

```html
<template is="dom-if" if="{{isUser}}">
  <div class="first-div">{{item.name}}</div>
  <div class="second-div">{{item.email}}</div>
  <div class="third-div">{{item.access}}</div>
</template>

<template is="dom-if" if="{{isProxyServer}">
  <div class="first-div">{{item.name}}</div>
  <div class="second-div">{{item.ip_address}}</div>
  <div class="third-div"></div>
</template>
```

Where isUser and isProxyServer might have to be computed property.  But you'll have to check if boolean is supported.

https://www.polymer-project.org/1.0/docs/devguide/properties.html#computed-properties

---

*[ufo/static/getItemsAjaxIntoList.html, line 74 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFVzPR_8Jv5TA1L3nQ:-KBFVzPR_8Jv5TA1L3nR:-1348269392) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/static/getItemsAjaxIntoList.html#L74)):*
As mentioned elsewhere, this name might be better with a simpler name.  Possibly "list-items"?

---

*[ufo/templates/landing2.html, line 4 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFNZhI3BvrxEUJFfCD:-KBFNZhJG9Zd_1aCeJrj:-1086089686) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/templates/landing2.html#L4)):*
This is a lot to look at here.  How about simplifying things a bit?  Such as:

```html
<list-items resources="{{user_resources}}"></items>
<list-items resources="{{proxy_server_resources}}"></items>
```

Where user_resources and proxy_server_resources are dict or objects that packages all the parameters here.  Of course, this will also require a constructor function in the polymer element to set the properties appropriately.

Another benefit, I think, is to maintain these information in the backend, instead of hard-coding them here.

---

*[ufo/user.py, line 145 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFU2o7lwMz-0Aj0S6i:-KBFU2o7lwMz-0Aj0S6j:683391973) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/user.py#L145)):*
Hmmm, how about providing this as a database api, instead of doing the operations here in the handler?  Such as "GetUsersAsDict()".  Then this whole code can be much simpler?

```python
users_json = json.dumps(({'items': GetUsersAsDict()}))
return flask.Response(users_json, mimetype='application/json')
```

Besides being much simpler to read, another benefit is that getting user in dict format can be re-used elsewhere.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-:-KBFXkfkca4477rcw_f3:979624371)*

**Comment by xwsxethan** [comment]
Thanks for the comments! Yeah I was able to do most everything easily. The one thing I'll circle back on is the proposed Polymer testing.

I still want to refactor the (now named) list-items custom element into two separate elements:
A list-items element, which will hold the ajax query and parsing into a paper-listbox; 
A paper-display element (I'm open to suggestions for a better name), which will hold the basic layout, including the toolbar at the top, button on the right, and then have list-items as a sub-element.
This change should hopefully allow for easier composition later as well as simpler readability.

---

Review status: 0 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[ufo/proxy_server.py, line 38 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFVGIpNx9h_CgYiz72:-KBFlo4O-heaLTJFHNyf:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/proxy_server.py#L38)):*
Done.

---

*[ufo/static/getItemsAjaxIntoList.html, line 1 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFWF1ZJ06gb6oaD2aM:-KBIsXWxXRdlx11Gnn5a:927132871) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/static/getItemsAjaxIntoList.html#L1)):*
This piece might be tougher to do than the rest. I'm likely going to refactor the custom element out into separate pieces anyway, so I'm going to hold off on this and see what you think later. I do think it needs to be tested, but I'm wondering how easily the methods above will work, versus say just writing a web driver test instead. There isn't any really fancy javascript going on here; just passing through X string goes in X place here, Y string goes in Y place there, etc. It is a lot of strings though, admittedly. I'll follow up with this once I've done the refactoring. Thanks!

---

*[ufo/static/getItemsAjaxIntoList.html, line 50 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFQSQZ7MoCvW_eixsC:-KBFm4MBAXPI6Hto2oJW:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/static/getItemsAjaxIntoList.html#L50)):*
Done.

---

*[ufo/static/getItemsAjaxIntoList.html, line 74 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFVzPR_8Jv5TA1L3nQ:-KBFm7vRYAvCkeGL_F5y:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/static/getItemsAjaxIntoList.html#L74)):*
Done.

---

*[ufo/templates/landing2.html, line 4 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFNZhI3BvrxEUJFfCD:-KBIokX1VkJnNKjaKHNO:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/templates/landing2.html#L4)):*
Done.

---

*[ufo/user.py, line 145 \[r4\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBFU2o7lwMz-0Aj0S6i:-KBIsLau4Mlv-5-liOAC:-499146009) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/ee338ceebb2156358f4d424a1630e8d3b35b9ee6/ufo/user.py#L145)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-:-KBIt5h07utvTxgc4EMe:-112243967)*

**Comment by blueandgold** [comment]
Very cool, looks super nice now!  :lgtm: 

---

Review status: 0 of 19 files reviewed at latest revision, 7 unresolved discussions.

---

*[ufo/routes.py, line 37 \[r5\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBJKGChq51sNEyKA7kM:-KBJKGChq51sNEyKA7kN:-1630848069) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/5446f56b039ea48565de3f7600f25ca00a63eaf0/ufo/routes.py#L37)):*
nit: there's a double red arrows here; should they be?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-:-KBJL82qDDvDkDQzP0S5:611805561)*

**Comment by xwsxethan** [comment]
Sorry for not assigning earlier, but please take a final look now to ensure everything is still as intended. Here's some screenshots of the latest version:
ufonewui05
ufonewui06

**Comment by blueandgold** [comment]
:+1: It looks good!

**Comment by xwsxethan** [comment]
Review status: 0 of 20 files reviewed at latest revision, 7 unresolved discussions.

---

*[ufo/routes.py, line 37 \[r5\]](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44#-KBJKGChq51sNEyKA7kM:-KBJlVbuXJEFjtp9_F90:833086574) ([raw file](https://github.com/uproxy/ufo-management-server-flask/blob/5446f56b039ea48565de3f7600f25ca00a63eaf0/ufo/routes.py#L37)):*
No, they shouldn't be there. My editor typically converts tabs to spaces, but it must have messed up. Fixed now. Thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/44)*

**Pull request merged**
