### PR TITLE
Hide the network jail setting until it's available.

### PR DESCRIPTION
**Pull request by blueandgold**
Save some head-scratching by hiding an unavailable option.  :)

---

This change is [Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/205)

### CODE REVIEW

**Comment by blueandgold** [comment]
@xwsxethan , there's a build error on this PR.  Can you please take a look?  Thanks!

**Comment by xwsxethan** [comment]
Can you double check that the functional tests pass with this removed? Specifically, just the SettingsComponentTest which I think is the only related one. If so, 👍 

As for the Travis error, if it is something in bower not pulling down a dependency, then it is a known issue. Just restart the process on the Travis page via the circle button, and it should fix itself.

**Comment by blueandgold** [comment]
The webdriver test actually did find a bug in the policy update handler.  Glad that we have them!

**Comment by xwsxethan** [comment]
Thanks and looks great! :+1:

**Pull request merged**
