### PR TITLE
Manual Production Release

### PR DESCRIPTION
**Pull request by xwsxethan**
Cross our fingers that this one passes!

---

This change is [Reviewable](https://reviewable.io/reviews/uproxy/ufo-management-server-flask/200)

### CODE REVIEW

**Comment by xwsxethan** [comment]
Finally it works!!!

**Comment by blueandgold** [comment]
:100:

**Comment by blueandgold** [comment]
Awesome effort here!

**Comment by xwsxethan** [comment]
Reviewed 106 of 106 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/ufo-management-server-flask/200)*

**Pull request merged**
